### ISSUE TITLE
Combining 'Engagement Tracking' with 'Outreach Tracking' docs

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#104]
### Project Description

We need to move toward a streamlined outreach tracking system that will take into account leads generated by engagement, content, and other sources. Document, which will be a spreadsheet, should contain no more than two sheets, one that has active prospects, the other that will serve as a repository for research and tracking.

The document should separate the intended goal of the outreach, have contact tracking, notes, affiliations, and other qualities.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Assess existing materials
- [ ] Decide on a new format
- [ ] Consolidate existing materials into one sheet (i.e. wishlist, engagement tracking, etc)
- [ ] Present new format to Ops team
- [ ] Begin using new format
- [ ] Tweak as needed

### Resources

- [link to project plan](#linkme)
- [SCRF: Outreach Tracking](https://docs.google.com/spreadsheets/d/1rdgqg_EGEKVw7WtGj57cvv77TYwQ6dtbogQEaEBNfZE/edit#gid=1886087855)
- [Deprecated Engagement Tracking sheet](https://docs.google.com/spreadsheets/d/15rPe5AumQKoFOCJZnQbOSUW3loczQTttR-W7P6X-lQo/edit#gid=0)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
Per discussion with @ghettodev I will try to have this complete for presentation on Wednesday 5/26 or Friday 5/28.

**Comment by eleventh19** [comment]
@jamesmcgirk can this be closed or are there any outstanding tasks?

**Comment by ghettodev** [comment]
merged with the existing outreach spreadsheet.
