### ISSUE TITLE
Project: General Grant Process Doc

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#108]
### Project Description

The goal of this project is to create a general grant process document that will serve as a template for any grant programs that SCRF launches, starting with Impact Awards, Pan African Grants, and others. The document will then be edited and shared on github. 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Eugene to review the grants process 
- [x] Impact awards team to meet
- [x] First impact award is issued
- [x] Grants process is updated 
- [x] Pan African grants team meeting 
- [ ] Pan African grants plan reviewed 
- [ ] Pan African grants process adjusted 
- [ ] Pan African grants pilot 
- [ ] Grants process is updated
- [ ] Any other information to add (SCRF view on grants?)

### Resources

- [link to grants overview and process doc](https://docs.google.com/document/d/1-Vu_VkQwqPcXXhGFVhyjbrJW177EfV_JRTUSdogRP9U/edit#)
- [grants project proposal template doc](https://docs.google.com/document/d/1lDCCDn-YdKm59cxohOiIIIL41RJvxvEI2n0NLEm85pw/edit)

### Ticket Updates
5/24/21 created the issue, linking to the grant doc, set up the impact awards meeting, planned Ishgun's work on creating a potential outreach list for Pan African grants

5/26/21 created a new template for grants project proposals

**Comment by eleventh19** [comment]
the draft has been created and updated a bit already. waiting to go through the process of the first grant issuance with impact awards and then Pan African grants, and then will revise

**Comment by eleventh19** [comment]
This is waiting on Pan African grants and on me reviewing the doc after the first Impact Awards

**Comment by eleventh19** [comment]
dropping this down to approved for now given that we're waiting on other cards to complete

**Comment by eleventh19** [comment]
Moving this to icebox for now. Once PAG gets ironed out and we're ready to add more regional grants, we will revisit

**Comment by encore9870** [comment]
tracked in smartcontractresearchforum/core-projects#45 now
