### ISSUE TITLE
Project: Create an Outreach Plan

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#111]
### Project Description

Outreach refers to the direct engagement of potential partners. The outreach process is designed to minimize overhead, identify blockers and trends and expedite integration.

### Work Plan

- [x] Create basic process
- [x]  Refine with Project Manager
- [ ]  Present to Rich (and Eric)
- [ ]  Present to Ops
- [ ]  Implement
- [ ]  Refine

### Resources

- [link to project plan](#linkme)
- [link to process doc/proof of concept](https://docs.google.com/document/d/1QyArl4-fMMYacqxtc2RCRwbcEawab2-La6EeY4dsyuo/edit)
- [link to any other relevant supporting materials](#linkme)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by encore9870** [comment]
No outreach activity has been updated to this ticket for over a year. I have reason to believe we should let it RIP.
