### ISSUE TITLE
Project: Branding Exercise / Other Material

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#113]
### Project Description

Conduct and record a series of interviews with SCRF researchers. Responses will be mined for emotional language, pleasure, and pain points about SCRF. The results of this interview will be used for developing revised outreach material.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Draw up questions
- [x] Schedule interviews with researchers
- [x] Interview researchers
- [x] Transcribe (electronically) the responses
- [x] Present results to Ops team

### Resources

- [link to project plan](https://docs.google.com/document/d/1rpKTUGmP1YjvFQdU_Wfkzd3EPTRwIMMQnaq8oYG6myY/edit#heading=h.6rk9efdwrrdj)
- [link to process doc/proof of concept](https://docs.google.com/presentation/d/1_dW0bGpLZLJGqp9VpYndKEVLwh6Z9VEBTbydvKW1QCg/edit#slide=id.p)
- [link to any other relevant supporting materials](#linkme)
- [Draft containing questions](https://docs.google.com/document/d/1rpKTUGmP1YjvFQdU_Wfkzd3EPTRwIMMQnaq8oYG6myY/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_
James to create a couple of questions designed to generate exciting new phrases/branding concepts about SCRF

**Comment by jamesmcgirk** [comment]
Eventually this should be combined with the Branding Exercise project.

**Comment by eleventh19** [comment]
@jamesmcgirk and @eleventh19 meeting on 6/29 to discuss plan

**Comment by ghettodev** [comment]
The project doc seems unfinished, can someone please turn that into a finished project plan.

**Comment by eleventh19** [comment]
Sure, I'll work on that

**Comment by jamesmcgirk** [comment]
I can get it started, I know you have a ton on your plate

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamesmcgirk** [comment]
Archive of [videos and my notes](https://drive.google.com/drive/u/1/folders/1rWsOPKhChUFmE8AFaRUt8UXsz-KEkcPq)

**Comment by eleventh19** [comment]
Interviews are underway. Looking to provide some update to the group next week

**Comment by jamesmcgirk** [comment]
Added [PPT](https://docs.google.com/presentation/d/1_dW0bGpLZLJGqp9VpYndKEVLwh6Z9VEBTbydvKW1QCg/edit#slide=id.p)

**Comment by jamesmcgirk** [comment]
E + I meeting to review the draft 7/29

**Comment by jamesmcgirk** [comment]
New language added to [the boilerplate doc](https://docs.google.com/document/d/1reyFhD-ncRtp4F5zhkjJIRjTdAWTrtodR0yEe1q7q7M/edit#heading=h.oooeapyb8e28)

**Comment by jamesmcgirk** [comment]
Moving this one to complete (since it's evolved into Maria's project)

**Comment by jamesmcgirk** [comment]
provided feedback on branding guide

**Comment by encore9870** [comment]
Disco team is handeling branding. Closing since the ticket is no longer relevant.
