### ISSUE TITLE
Project: Facilitating Undergraduate Blockchain Courses with Content Support

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#122]
### Project Description

This is a project for SCRF to enter into the undergraduate academic space, provide academic value to students, find potential candidates for our research grants, and establish a strong presence with professors, students, and universities. The goal is for SCRF to facilitate new and upcoming courses with resources to improve their academic offerings.

### Work Plan

- [x] Look into existing coursework offerings across universities in the U.S and brainstorm out how SCRF can be involved
- [x] Create an external facing document (which could be shared with professors while discussing the idea) that outlines the exact offerings that we plan on providing. 
- [ ] Create a 6 month logistical plan on how this project can practically be implemented. Explore topics like what would the pilot look like? How many resources would we need to execute this? How long would implementation take? What are the next steps?

### Resources

- [link to doc on current course offerings and brainstorming](https://docs.google.com/document/d/111BaZGVITOrrDFmwWSlNe7frODI_w26VOzLfFfIN7OE/edit#heading=h.vwid6armfbam)
- [link to external facing doc with specifications on the project offering](https://docs.google.com/document/d/1_loRWhGZeBsGgbPMeR9B3Ko0WG7nTI1I20OLVEwfU-U/edit#heading=h.9iv5ds9kf16a)

**Comment by encore9870** [comment]
Archiving by closing. A good reference for the future.
