### ISSUE TITLE
Project: Aligning SCRF with Blockchain Clubs 

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#123]
### Project Description

One of SCRF's goals is to generate student engagement on the forum while providing value to students. This project explores the possibility of achieving the goal by starting various initiatives by involving blockchain clubs.

### Work Plan

- [x] Explore the major initiatives of tier 1 and tier 2 blockchain clubs (narrow down the common initiatives across all clubs) and gather data on their leadership team, focus area etc.
- [x] Plan out a couple of engagement plans for aligning SCRF with these blockchain clubs 
- [ ] Create a 6 month logistical plan on how this project can practically be implemented. Explore topics like what would the pilot look like? How many resources would we need to execute this? How long would implementation take? What are the next steps?

### Resources

- [link to doc exploring top 18 blockchain clubs in the US and potential engagement plans for SCRF](https://docs.google.com/document/d/1tmqosJfdAxIpqXoj6PHMym1dYsr6J9Soei5Uv1f2KoY/edit#)

**Comment by encore9870** [comment]
Archiving by closing. A good reference for the future.
