### ISSUE TITLE
Project: Explore the possibility of entering the Indian Blockchain Market

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#124]
### Project Description

India is experiencing an expedited boom in the crypto market, specially in the academic/education space. There are many opportunities for SCRF to be involved, generate value for other, and gain traction itself. This project is meant to explore this possibility by studying the Indian Blockchain Landscape and beginning engagement with high value individuals in India.

### Work Plan

- [x] Research and prepare a document on the current state of crypto and blockchain in India (legal, demographic, academic etc.)
- [x] Explore the corporate sector in India in the blockchain market and present the findings.
- [x] Deeply analyse the blockchain education sector in India by looking into courses and research ongoing in govt. organizations and private projects.
- [x] Write down ideas for SCRF's involvement in the Indian Blockchain Sector. 
- [x] Prepare an outreach sheet with high value individuals in the sector.
- [x] Begin outreach and follow up to learn more about the market and explore potential opportunities to collaborate.  
- [ ] Continue outreach initiatives and exploration until a definitive project is found. 

### Resources

- [An in depth study of the Indian Blockchain Landscape and Ideas for SCRF's involvement ](https://docs.google.com/document/d/1YxPphWg652GlriZDiXYhlwUomE7C1sXf8cY21kfn_jw/edit)
- [Outreach sheet for high value Individuals in India](https://docs.google.com/spreadsheets/d/1xKnsBmuZdHBY_BaSkG9JEQdXACiNmgVGHqnyticZcT8/edit#gid=1046166402)
- [Outreach doc for Arun Reddy, a tech consultant with the Indian Govt.](https://docs.google.com/document/d/155-aj5xcSOTDg3j8XkJXed-RYQBnQ-DKMOK0Q0KuU_s/edit#heading=h.qvllm64d36jq)

**Comment by encore9870** [comment]
Closing since the internship has been completed and this is no longer relevant.
