### ISSUE TITLE
Project: Tracking and updating our GitHub Public Repository and HackMD Docs

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#125]
### Project Description

We want all of our public facing docs to reside in the docs repo in absence of us having a proper website. To achieve this, we need to track the status of our docs, convert docs from google drive --> markdown --> GitHub, and keep our tickets on GitHub up to date. 

### Work Plan

- [x] Meet with the leads of every SCRF team to identify all public facing docs for that team
- [x] Categorize these docs based on docs already on GitHub, docs on HackMD, and docs almost ready to be converted to markdown
- [x] Update the tickets associated with every doc based on the work completed for that particular project. 
- [x] Suggest edits to docs on HackMD based on the style guide 
- [ ] Continue updated GitHub tickets with status on the documents, continue converting public facing docs to markdown --> gitHub, and keep the original document linked below updated with the status on all these tasks. 

### Resources

- [Public Documentation Pipeline](https://docs.google.com/document/d/1WSKokXrzjcwAXd38EWdx2CU7S0bYQV0xdjseQmM8bcg/edit#)

**Comment by encore9870** [comment]
This is now worked by the discovery team and their messaging borad.
