### ISSUE TITLE
Project: Ishgun's work during Summer 2021

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#126]
### Project Description

Ishgun's internship was the very first internship at SCRF, and we can use it as template to structure other internships at SCRF. Thus, it is essential to keep track of everything he's done. This task is also important to ensure that we do not loose momentum of the projects he started at SCRF. 

### Work Plan

- [x] Write down Ishgun's work in detail, week by week.
- [x] Include links and descriptions to all projects and documents that Ishgun Prepared.
- [x] Add Github Tickets for all the projects that Ishgun started.

### Resources

- [Ishgun's work at SCRF, Summer'21](https://docs.google.com/document/d/1R0Bz80iOoaozRU0lJCZsKjRw6PCbK0wTawOHstgpUgQ/edit#)

**Comment by encore9870** [comment]
Closing the ticket since the internship is finished. Thanks for granting access to your precious documentation. I've added it to our drive for developing future internship programs.
