### ISSUE TITLE
Project: Rating top blockchain academic journals and tallying most common journals referenced on SCRF

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#128]
### Project Description

It is important to keep track of which journals we've been referencing the most at SCRF so that we can try to reference papers from other good journals as well. But since there is no standard way to analyze the usefulness of other journals for our purposes, we should self devise criteria that works for us and rate these journals accordingly. 

### Work Plan

- [x] Compile a list of top blockchain academic journals, categorized on the basis of subject 
- [x] Devise a criteria to rate these journals in terms of usefulness to SCRF and allocate scores accordingly.
- [x] Tally most common journals referenced on SCRF.

### Resources

- [Academic Paper Sources](https://docs.google.com/spreadsheets/d/1nRI0YVXLKR1dZ3qgBldqMMoC5yoZdjAs7OOjwpOkkIg/edit#gid=0)

**Comment by encore9870** [comment]
Archiving by closing. A good reference for the future.
