### ISSUE TITLE
Project: Research Pulse Authors Data Collection

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#131]
### Project Description

It's important for SCRF to have information available about our research pulse authors for potential engagement, outreach, awards programs, etc. Thus, compiling detailed data on each RP author would come in handy. 

### Work Plan

- [x] Identify three most significant papers in every RP
- [x] Find and compile information about each author for those three papers (per RP issue)
- [ ] Continue doing this for every RP (weekly task) and provide updates in the comments section.

### Resources

- [Research Pulse Authors Data Collection](https://docs.google.com/spreadsheets/d/1rdgqg_EGEKVw7WtGj57cvv77TYwQ6dtbogQEaEBNfZE/edit#gid=1565368706)

**Comment by ishgun178** [comment]
I have completed this task for RP #14, #15, and #16 as of July 1st, 2021.

**Comment by eleventh19** [comment]
We need to figure out a better process to support this. We will see if we can get someone to help find the outreach info for the highlighted research pulse authors. Then we can establish a process

**Comment by encore9870** [comment]
We are doing this in the content team, and sharing it with Discovery. Closing this since it's not tracking further progress.
