### ISSUE TITLE
Project: Project Management Job Description Creation

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#132]
### Project Description

*Describe the idea/project in no less than 200 characters*. Please be very specific about precisely what the project does, and why it exists.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] create github ticket
- [x] create intial draft 
- [x] share with ops team 
- [x] incorporate feedback
- [x] create public facing copy 
- [x] convert to md
- [x] upload to github 

### Resources

- [link to project plan](https://docs.google.com/document/d/1CGzkpDBts359cH6yEQstJrwsgdfnqewZWxBYI34gKwo/edit#heading=h.l899m8k3v6mr)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by ghettodev** [comment]
I've added my revisions

**Comment by ghettodev** [comment]
Posted to the repo: https://github.com/smartcontractresearchforum/docs/commit/8d270e957b80aedec8991165fe0accfe0278fb9d

**Comment by eleventh19** [comment]
Closing this as the job description was posted. Deane just created a few additional versions. If we see that we need to explore more job descriptions now, we can add another card to capture that
