### ISSUE TITLE
Project: Develop all onboarding material

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#133]
### Project Description

The current onboarding material is designed for research fellows, as more casual users come into the fold they will need onboarding too.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Review existing onboarding materials
- [x] Discuss requirements
- [x] Develop a PPT designed for the weekly onboarding calls
- [x] Develop a workflow
- [x] Onboarding call
- [x] Develop events and personnel needs
- [x] Present to Ops
- [ ] Tweak per ops suggestions
- [ ] Markdown
- [x] Soft Deadline July 30, 2021
- [x] Hard Deadline August 5, 2021
### Resources

- [Project Plan Doc](https://docs.google.com/document/d/1fifCQ_UkfASYzDiYic6HaTLA4kwKjCFqe1nwlVyTPFg/edit#)
- [Onboarding Process Doc Draft](https://docs.google.com/document/d/1J53ID6E23-WYKr0q0r-Pt5qlU6_fiHG3syI-0hwAr0c/edit#heading=h.z4x93e9tg645)
- [Draft ReadMe and Table of Contents](https://docs.google.com/document/d/1wgTn0h9WQ3dA_vxnUqX_TAAQKt-ufP4E1e7r0qOlcqg/edit#)
- [Existing Onboarding Docs](https://docs.google.com/document/d/1IAzayg9tJ_kj_nR1WTjyCpjc3EcJW0CjqMnSqRTyY44/edit)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
@zubepaul Rich asked me to lend a hand developing materials - I'll start looking at Ishgun's stuff, we can talk about what we're missing... Eugene and I are talking about doing weekly onboarding calls so I'm thinking we'll need a slide deck for those calls... we'll need work flow doc... and we can incorporate the existing [onboarding tracking sheet](https://docs.google.com/spreadsheets/d/1e-MjEFGD_K4sBkQCraSJeYLwjy3_uJNctPtrzO1f4vI/edit#gid=0)

**Comment by zubepaul** [comment]
I created a new Doc in SCRF Process and linked it to the ticket.

**Comment by zubepaul** [comment]
Connecting @loicdrbx to this ticket

**Comment by zubepaul** [comment]
Adding @eleventh19

**Comment by jamesmcgirk** [comment]
Here's my draft of the [onboarding workflow](https://docs.google.com/document/d/17035o0TTzNhbvJQzyFX1YzQCgrcKCGB4wtiCDd32FNc/edit#) - we can consolidate this evening

**Comment by zubepaul** [comment]
Updated ticket with additional resources and drafts.

**Comment by jamesmcgirk** [comment]
I'll create a basic powerpoint for our calls next

**Comment by jamesmcgirk** [comment]
Here's a draft of the [onboarding ppt](https://docs.google.com/presentation/d/1t8vXP7eGX7v_XWVciwMpmBLM-U4r7gVvYEEqu_Y3u6w/edit#slide=id.gbfb9e96628_0_113) - the plan is to use this during community calls for recruitment

**Comment by zubepaul** [comment]
Creating outward facing doc drafts in community folder

**Comment by zubepaul** [comment]
Updated Existing Onboarding Docs with some additional found documents

**Comment by zubepaul** [comment]
Onboarding Process Doc Draft is now being used to collect notes and coordinate efforts.
@eleventh19 is working on creating external language
@jamesmcgirk is working on a Forum post draft for onboarding
@zubepaul is working on a table of contents and micro-section drafts

**Comment by zubepaul** [comment]
Soft deadline of July 30th has been added.
Hard deadline of August 5th has been added.

**Comment by jamesmcgirk** [comment]
Moved to in progress per Rich's suggestion

**Comment by zubepaul** [comment]
Created a table of contents doc to help manage various mini-pages for onboarding material. Separated this from the onboarding process doc so it can focus on the process of onboarding. Linke below and also added to the resources above. 
https://docs.google.com/document/d/1wgTn0h9WQ3dA_vxnUqX_TAAQKt-ufP4E1e7r0qOlcqg/edit#

**Comment by zubepaul** [comment]
@Coinproz This ticket is where I am trying to pull together all onboarding documents, and your idea of visualizing this is a great idea.

**Comment by zubepaul** [comment]
ReadMe and Table of contents doc has been updated with additional links. Please review for completeness. @Coinproz it would particularly help to have you take a look at this while you are thinking of your visualization.

**Comment by jamesmcgirk** [comment]
First stab at [How to Get Paid](https://docs.google.com/document/d/1nlJ6OZuO64stQ4RvbOfbL1YxEp-M8Sh33lS3-L5NIhc/edit#)

**Comment by jamesmcgirk** [comment]
Adding Rich's edits, including a new section about where to find work on SCRF

**Comment by zubepaul** [comment]
Document prioritization:
1. Welcome to SCRF
2. About SCRF
3. Contributor Projects and Templates
4. How to get paid

**Comment by zubepaul** [comment]
How to get paid updated and moved to Hackmd. Ready for publication to repo

**Comment by zubepaul** [comment]
Discussion Post template is ready for final review in Hackmd @ghettodev 
https://hackmd.io/QyvdKk9ZTTm9DO-dofRM-w

**Comment by jamesmcgirk** [comment]
Edit of How to Communicate, further edits needed? Working on new language for 1 + 2 boilerplate with Eugene

**Comment by zubepaul** [comment]
Additional "How to Communicate" edits added. Changed to "Connecting With Us" in ToC doc. @jamesmcgirk could you please help with tone and style similarity checks and some content suggestions?

**Comment by jamesmcgirk** [comment]
@zubepaul fleshed out the missing content, made some edits, will replace the boilerplate once/if it's approved; let me know if my edits are in the direction you're hoping for - I like info pages to be as streamlined as possible, so I may have cut too much context. Suggest leaving the Forum on top just because we want to encourage people to use the forum as much as possible; I'd follow with Chat, Meetings, Github, Socials

**Comment by zubepaul** [comment]
Compensation page needs to be updated with tracking docs and contributor agreement

**Comment by eleventh19** [comment]
> Compensation page needs to be updated with tracking docs and contributor agreement

Also a link to a hours tracking template with language ~"Create a copy of [this hours template](https://docs.google.com/spreadsheets/d/19CmaqELKS_S2gWQIs2kddA91rv5zca-51mk_sOJ0gYs/edit#gid=0) and share with your supervisor, Rich, and Eugene."

**Comment by jamesmcgirk** [comment]
@eleventh19 @zubepaul I'll update the onboarding presentations

**Comment by zubepaul** [comment]
Editing and updating Hackmd docs for 8/2

**Comment by jamesmcgirk** [comment]
Edit of How to get paid and Communicate with Us... let me know if you need anything else...

**Comment by jamesmcgirk** [comment]
Quick check of Community Calls

**Comment by zubepaul** [comment]
Essential documents (as determined by a meeting) converted to markdown and ready for repo 
@ghettodev

**Comment by zubepaul** [comment]
Onboarding Process document updated and ready for review. https://docs.google.com/document/d/1J53ID6E23-WYKr0q0r-Pt5qlU6_fiHG3syI-0hwAr0c/

**Comment by zubepaul** [comment]
Process proposed to Ops. Making refinements and preparing for socializing to the community.

**Comment by zubepaul** [comment]
Onboarding spreadsheet updated to reflect checklist

**Comment by zubepaul** [comment]
Create a GitHub template for all GitHub documentation. @jamesmcgirk can you assist?

**Comment by jamesmcgirk** [comment]
@zubepaul I think @loicdrbx was asked to help with this. Have divided the original onboarding PPT into a couple of versions, one for community calls, one for the document pipeline, one for project pipeline. Need to have a discussion at some point about whether these align with the new structure

**Comment by loicdrbx** [comment]
@jamesmcgirk I don't remember being asked to help with that task, but I'd be glad to assist. What exactly needs to be done?

**Comment by zubepaul** [comment]
@loicdrbx I believe @jamesmcgirk was referring to the GitHub template for documentation. I am working with Maria at the moment to help match what that template looks like with what the branding looks like, but it would potentially be beneficial to get @loicdrbx's perspectives on it as well.

**Comment by jamesmcgirk** [comment]
@loicdrbx what Paul said above! Sorry to tag you in this thread

**Comment by eleventh19** [comment]
so I think Maria is working on this. I can't tag her yet here (she's going to link me to her git soon). this is the template [she's made so far](https://docs.google.com/document/d/1AsU3r7v1S1r6I3IFXG6l0VLlePnWVyRLFOkgWxlmrSU/edit). feel free to comment in the doc

**Comment by zubepaul** [comment]
Tagged the people who are actively engaged in creating onboarding documentation for review of the process document for outward-facing documentation.

**Comment by zubepaul** [comment]
Paul to create a rough visualization of what are all the actors and stages and needs of onboarding to help get people on the same page between onboarding, documentation production, outward facing templates, checklists, automation needs to put the internal onboarding team (and for global teams).

**Comment by zubepaul** [comment]
Finalize the external-facing documentation of onboarding process.

**Comment by jamesmcgirk** [comment]
Add a note to get Discord access for onboarded core researchers / Ops

**Comment by eleventh19** [comment]
adding @ttaloute as she's working on onboarding now

**Comment by jamesmcgirk** [comment]
@jamesmcgirk create a few slides for the Creating Content presentation that explain how to create comments (to foreground their importance)

**Comment by zubepaul** [comment]
Working on the external documentation of levels, roles, and onboarding tasks associated with each with @eleventh19 and @ttaloute

**Comment by eleventh19** [comment]
@ttaloute created [this sheet](https://docs.google.com/spreadsheets/d/1Tp_A8dXioz5uc9sJ7kY3lWia59GGO_ckar1hWCDYjO0/edit#gid=1283322459) outlining onboarding activities that @zubepaul @jamesmcgirk @LorrettaGS and others are reviewing for now. 

We also had a wider team meeting with folks working on onboarding, community, and branding today and have another one scheduled on Thursday

**Comment by encore9870** [comment]
We might be experimenting with creating a google form to onboard new members. 

Google forms could be great because they can serve as a checklist that reminds you to fill in everything. It also makes it easier to collect or organize contact information and see if they are onboarded.

Here's [a Google form for onboarding community members](https://docs.google.com/forms/d/e/1FAIpQLSdwLgsLRAeCqkGwxgEU2pp2hEy_LB8Kw8kKmd4Q7sg-XLz2CA/viewform). It is almost Eugene's checklist with slight modifications to reflect @ttaloute 's latest version.

I've also created one for [onboarding contributors and core members](https://docs.google.com/forms/d/e/1FAIpQLSfoFaySwksojzSAXaG_6aBG5VdDkV58bZ5eHEWbURLAbQwTOg/viewform) based on the previous checklist we had. However, in the new version, contributors and core members do not share the same onboarding process.

**Comment by jamesmcgirk** [comment]
@ttaloute and @eleventh19 have requested a content generation training video.

- [x] Query researchers for feedback on the current training program
- [ ] Develop basic script
- [ ] Shoot the script
- [ ] Review and Edit
- [ ] Send to Audio Production
- [ ] Publish

Link to [script doc](https://docs.google.com/document/d/1jL-mJOToaW7nZuBI2zIuf39G3_fuTqoqzEXwwZSKmtU/edit)

**Comment by encore9870** [comment]
We had a meeting on 10/21. @ttalloute and @twan-dev are putting together a process based on the discussion that took place. We will update on Tuesday.

**Comment by encore9870** [comment]
### Current state 

- After the meeting on 10/21 and more work from Tania, we now have a pipeline (powered by google forms + email templates) that future applicants will all be required to go through. About 7 new applicants and they will go through the process and we'll see how they do.

- I will make the content generation training video.

**Comment by jamesmcgirk** [comment]
Per today's discussion, I'll begin working on an outline of a SCRF culture presentation

**Comment by eleventh19** [comment]
met with @ttaloute this week to discuss what documentation needs to get created before 12/20, focusing on the outward facing info on how to apply for a research summary grant, what to do once accepted (in the form of a welcome email/maybe a doc), and what resources researchers have available to them (glossary, office hours, etc.). need to make sure the revised content pipeline expectations that @twan-dev are incorporated into the onboarding docs as well

**Comment by zubepaul** [comment]
Closing this ticket and replacing it with issue [218](https://github.com/smartcontractresearchforum/engagement/issues/94)
