### ISSUE TITLE
Project: Create 'Salon' threads with highlights from Discord intended to start conversations

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#134]
### Project Description

Problem: great discussions occurring on Discord that aren't making the leap into forum. A potential solution: creating general purpose 'salon' threads which will contain excerpts of the Discord conversations, and other chat starters.

### Work Plan

- [ ] Create the threads
- [ ] Assign salon hosts
- [ ] Assess after one week
- [ ] Tweak, Keep or Delete

### Resources

- [link to project plan](#linkme)
- [link to process doc/proof of concept](#linkme)
- [link to any other relevant supporting materials](#linkme)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
Suggested as a good project for Loic.

**Comment by jamesmcgirk** [comment]
@jamesmcgirk find Loic's GH and see if he wants to do this

**Comment by eleventh19** [comment]
> @jamesmcgirk find Loic's GH and see if he wants to do this

Just caught up with Loïc - he'll be sharing his git handle soon and wants to try this for IoT-related discussions.

**Comment by loicdrbx** [comment]
@James McGirk ***@***.***>  My github username is
loicdrbx

**Comment by jamesmcgirk** [comment]
Thanks, Loic! Looking forward to helping you with this one

**Comment by jamesmcgirk** [comment]
@29988122 posted a great question about installing L2 networks on Discord 7/27 7:26pm UTC+3

**Comment by zubepaul** [comment]
Link to project #150

**Comment by encore9870** [comment]
Good idea but no longer relevant. Let me know if we should not be closing it!
