### ISSUE TITLE
Project: Create Bot(s) for Discord Server

### ISSUE THREAD

**Issue by loicdrbx** [smartcontractresearchforum/research_team#153]
### Project Description

Create bot(s) to automate tasks and foster engagement on the Discord server. Using bots may reduce the workload of moderators by taking care of repetitive announcements and reminders. This may also incentivise engagement by identifying, tracking, and rewarding active members.

####  Potential Features

-   Welcome to server message
	-   Acknowledge server rules before access is granted
-   Scheduled messages (ex: reminder for end of month invoicing)
-   Self-selection of roles/interests (ex: ethnographer, ethereum, etc)
-   Track and reward engagement levels
	-   Leaderboard
	-   Level-based rewards (ex: custom roles, access to additional channels)
-   Announcement for calendar events

####  Potential Bots

|                                                            | [MEE6 Bot](https://mee6.xyz/) | [Dyno Bot](https://dyno.gg/) | [Sesh Bot](https://sesh.fyi/) |
|--------------------------------------------------|------------------------------------------|------------------------------|-------------------------------|
| Welcome to server message             | ✓                                               | ✓                                 | x                                  |
| Scheduled messages                        |     *                                            | *                                  | ✓                                  |
| Roles/interests selection                    | ✓                                              | ✓                                 | x                                   |
| Tracking and rewarding engagement | ✓                                             | x                                  | x                                   |
| Announcements for calendar events | x                                               | x                                  | ✓                                  |

>**Time intervals can only be set in minutes*

### Work Plan

- [x] Gather feedback on the features and bots that have been identified
- [x] Decide on the bot or set of bots that works best for the server's needs
- [x] Integrate the selected bot(s) and features into the Discord server

### Closure
New Chat Project Board
https://github.com/orgs/smartcontractresearchforum/projects/31

New Chat Issues
https://github.com/smartcontractresearchforum/engagement/issues/new/choose

**Comment by eleventh19** [comment]
link with #168 as that's exploring what is happening with discord updates. this is the [write up](https://docs.google.com/document/d/1QqyujQ_utvM6IyebQdUB_-Qr1fxeEV_bKG6J9pz1Zdo/edit) that Loïc made

**Comment by eleventh19** [comment]
@nakedwinnie

**Comment by nakedwinnie** [comment]
Added Carl Bot to potential bots table

**Comment by nakedwinnie** [comment]
Added automated Welcome to Server Message

**Comment by nakedwinnie** [comment]
Added automated Acknowledgement of Server Rules message

**Comment by zubepaul** [comment]
This is not a pressing issues, but I added @brianalexakis for future thinking and working on.

**Comment by SirAh0** [comment]
Information can be found in the [🔗](https://emojipedia.org/link/)[Chat Project Plan](https://docs.google.com/document/d/1c5EhvYxpSyNuZZv0fX-KTmDv1OtawzWV/edit?usp=sharing&ouid=107935953561747433773&rtpof=true&sd=true)

We should close this issue and I will open new ones as Chat moves forward.

**Comment by SirAh0** [comment]
New Chat Project Board
https://github.com/orgs/smartcontractresearchforum/projects/31

New Chat Issues
https://github.com/smartcontractresearchforum/engagement/issues/new/choose
