### ISSUE TITLE
Building out a mentorship program

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#167]
This is a card to coordinate all of the aspects mentorship program that Deane is getting started. Deane has already:
* started doing open office hours twice a week (check out public calendar) 
* creating a general curriculum 
* creating a research prospectus 

The next steps are to:
- [x] refine the docs
- [x] link to all of them here
- [x] get the docs on a shared drive
- [x] figure out which docs go on github
- [x] get drafted in HackMD
- [x] review all docs (Deane, Eugene, Rich, input from anyone else)
- [x] upload to github
- [x] do we want a forum post announcing this?
- [x] do we want socials or other announcements?
- [x] do we need any additional support for the program?
- [x] get the first cohort in place

**Comment by eleventh19** [comment]
@DeaneDesper is the main project owner

**Comment by eleventh19** [comment]
Meeting with @DeaneDesper to review the current state of the docs. Will add links here. From there, we'll create public documentation and will start running the program over the 8-12 weeks. We're also having some additional support for the mentorship program so will tag here once confirmed

**Comment by eleventh19** [comment]
@DeaneDesper can you please add your updates as a comment here. Going to ask @LorrettaEGS for some help project managing this and @ralphlombreglia will meet with Deane by next week. Deane, Lorretta, and I will meet to refine the process/PM components. Need to write out expectations for participants

**Comment by DeaneDesper** [comment]
@eleventh19 Are you referring to the project plan that is revised in the shared folder?

**Comment by DeaneDesper** [comment]
Engagement: The researcher mentorship cohort will provide new junior researchers with the necessary knowledge and skills to produce scholarly research summaries and articles. The engagement with the mentor and senior researchers will be ongoing and on a regular basis. The researcher mentorship cohort program provides current and new researchers to engage and learn from each other to build community.  In addition, the participants will be engaged with other researchers not to just include other members of the cohort.

**Comment by DeaneDesper** [comment]
Junior researchers will gain knowledge in the following areas:
Contributing to Discord discussions
Introduction to research pathways
Defining a research problem
Conducting summaries of academic journals
Navigating the publication process
In addition, junior researchers join a broader peer community, and may be invited to virtual networking events, and summits.

**Comment by DeaneDesper** [comment]
Benefits:
The benefits of the researcher mentorship cohort allow the junior researchers to work with an experienced research mentor.  Junior researchers are matched into a cohort, a mentor and small group of peers who are at a similar academic stage and interested in the same research area.
Cohorts will identify opportunities around various topics, shared by each junior researcher and supported by the mentor through group and one-on-one meetings.
Mentoring is a proven approach to accelerate development while increasing retention, engagement, and productivity.
 
Phases of the researcher workshop 101:

Phase One - Introductions to SCRF
Mid Point Session - training from outside sources 
Phase Two - Building the summary

Learning objectives and outcomes per phase: 
Researcher Workshop 101 Milestones:
Phase One - Initial post in the discussion forum 
Phase Two -  Publish a summary

**Comment by eleventh19** [comment]
I need to review the most recent docs that Deane sent. will link to them here

**Comment by eleventh19** [comment]
> @eleventh19 Are you referring to the project plan that is revised in the shared folder?

Yes please, link to the relevant project documentation here (or to the overall folder if that's easier).

**Comment by eleventh19** [comment]
updated the [project plan](https://docs.google.com/document/d/18gUBhoQKLaJ4FULeZCLKcwX2wS1Xd_wNqbncBRxmDAA/edit#) with a process for participants to follow. will review with @DeaneDesper tomorrow

**Comment by eleventh19** [comment]
added a new [drive folder](https://drive.google.com/drive/folders/13a5LWxB4JnAsY3bz7UPWyCqoMxL-n-0i?usp=sharing) where all of the information for the mentorship program will be housed. this includes the overall process doc, the [sign up sheet](https://docs.google.com/document/d/1U88KyIYHOBMwARbpPT0Eg2vJfWu5VdgEmvfamlazwjQ/edit#heading=h.9gjoy33mcsvk), the [application draft](https://docs.google.com/forms/d/1TVdHc5MDlIEWEYd3V3VSEnh87T38Iwqx_84Fii4KX28/edit), as well as the documents to be used in the workshop itself:

- [Syllabus / mentorship outcomes](https://docs.google.com/document/d/1VwqmrTGdYPY5a8kGM8zLmvJ6TeT3hZzOVLN8p7MeWhM/edit)
- Research method and design ppt
- Paraphrasing examples
- CF-TF
- Annotated bibliography
- Meal plan
- Reference list
- Researcher WS_101_Tracking Status
- Change matrix

refining the process and getting ready to launch the pilot on 10/16, will be sharing the application within our community in the next few days

**Comment by eleventh19** [comment]
@LorrettaGS, @twan-dev, @vsterling can one of you help with reviewing the [syllabus](https://docs.google.com/document/d/1VwqmrTGdYPY5a8kGM8zLmvJ6TeT3hZzOVLN8p7MeWhM/edit) (generally and also to help format) and someone also help review the process (bottom of [this doc](https://docs.google.com/document/d/18gUBhoQKLaJ4FULeZCLKcwX2wS1Xd_wNqbncBRxmDAA/edit#heading=h.fwidqwd39xae)) to see if you can spot any obvious gaps.

**Comment by vsterling** [comment]
@eleventh19 I'll review and help format the syllabus

**Comment by LorrettaGS** [comment]
@eleventh19 and @vsterling, I will review as well.

**Comment by eleventh19** [comment]
Edits are taking place, a few more minor revisions left. Then going to get a version of the syllabus into HackMD. starting to share the application this week

**Comment by eleventh19** [comment]
The pilot program has launched as of 9a EST this morning (Oct. 16th) with all 15 participants in attendance. 

There is a new mentorship repo (not public during the pilot) that is used to track people through the program. The ops team has the breakdown of who applied, was accepted, and who got me the sign up sheets (most of the group). 

We are going to create a new card to track the 101 program through December when the program wraps, those who complete will off board and invoice for their honorarium, participants will provide feedback, and then we'll create a new issue/card for the next phase (running round 2 of 101 and launching a new course).

We are speaking to 1-2 people who might join to help grow the mentorship team at SCRF, updates to come in subsequent cards. 

For any questions relating to the mentorship research program itself, reach out to @DeaneDesper. For any other questions, reach out to @LorrettaGS or @eleventh19

The one outstanding task from this card is to get the syllabus cleaned up and shared on our github. @rjx223 is helping with that and that will be uploaded this week

**Comment by rjx223** [comment]
Final edits made. The document has been converted and is ready for final approval
