### ISSUE TITLE
Project: Recording some initial trainings and mapping what training videos we need 

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#182]
### Project Description

This project card is to outline the initial training videos that are being created initially and to map out the issues that will be created. 

### Work Plan

- [x] Record a how to get comp'ed video
- [ ] Record a general github training 
- [x] Record a mentorship PM github training 
- [x] Record general PM github training 
- [ ] Coordinate on a content pipeline PM training 
- [ ] Plan what other recordings are needed (and if they're part of this card or if a new card starts to capture those) 

### Resources

- First training video - [how to get compensated](https://youtu.be/2ecSFKyJFW4)

**Comment by eleventh19** [comment]
There is also a pm training video and a mentor ship program training video. Working on the content pipeline training

**Comment by encore9870** [comment]
Important project! Closing this since it's not been actively worked on, most videos have been created.
