### ISSUE TITLE
Training New Content Pipeline Project Manager

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_team#185]
### Project Description

- Train a new project manager to take over document pipeline
- Define best practices for document pipeline management

### Work Plan

- [x] Define the current role
- [x] Define the ideal role
- [x] 1-1 meetings with stakeholders

### Resources
[Onboarding into the Content Pipeline](https://docs.google.com/document/d/1IQKBGB7d-QosIhQz5MLVSrL9W1Qen4sIgVOFQn6Sye4/edit#heading=h.2cknjg4yrlmz)

[SCRF: Process - Content Publishing Workflow](https://docs.google.com/document/d/1Dxl4mpLQ01QrSvJC7HAl3xWR92aiIo4QgFwyk9w53Hk/edit#heading=h.hx4ss3adaomk)

**Comment by eleventh19** [comment]
Rich, Lucas, Twan, and I are meeting a few times to get us all on the same page with the content pipeline and process. @twan-dev anything specific that we can do for now?

**Comment by encore9870** [comment]
@eleventh19 Yes, Lucas and I met 12 hours ago. We are going to clear up the tickets in the ideal proposal stage starting by asking people to stay compliant with their formats. 
I've created a [spreadsheet](https://docs.google.com/spreadsheets/d/1G4laGaZ9X89-PiNDLpdfUgZXKVsYqpFA7QxaFNLa5wI/edit#gid=0) to keep track of what to follow up with Lucas

**Comment by encore9870** [comment]
- During our last pipeline meeting, we discussed and settled with v1 rules to our content pipeline
- Over the past week, I have been making sure new tickets comply with those rules
- We are having our researchers' call in 12 hours

Things to do
- [x] Settle with a time for future regular researchers' call
- [x] Discuss observations from implementing v1 rules
- [x] Create a tutorial for the new rules (belongs to onboarding ticket instead)

**Comment by encore9870** [comment]
Last call went well. We discussed the new rules and mostly the peer review part.
As there have been updates to v1 rules, creation of the tutorial will start this week.
Regular time for researchers' call tentatively proposed. I will check the box when it's properly settled.

**Comment by encore9870** [comment]
Many things have been accomplished within the 49 days since the creation of this ticket. 
I have learned a lot from many important people that contribute to the pipeline and we are actively working together to make the pipeline better. 

Important updates that have been or are currently rolling out
- Creating and running a standard for all the tickets that go through the content pipeline. This speaks about the information that needs to be communicated and the checks that have to be passed
- Accelerating tickets to the next stage to avoid bottlenecks e.g. moving tickets from drafting directly to FCR if there are no peer reviewers. More to come 
- Updating tools in Github to serve our use case better

General directions that are going to be impactful to future changes
- Raising the bar of content that goes in and comes out of the pipeline
- Eliminating all bottlenecks by creating universal standards of content and effective delegation of content review and approval
