### ISSUE TITLE
Epic: Create Initial Forum Maintenance Plan

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#191]
**Description**
An initial description of the maintenance tasks, responsibilities, and processes associate with forum maintenance in the moderation team. 

**Steps**
- [x] Create Maintenance Plan with a list of maintenance items
- [ ] Create a rotation policy and process for accomplishing Maintenance Plan
- [ ] Create a schedule for maintenance items
- [ ] Produce above documentation and determine if it becomes public.

**Resources**
- [Forum Maintenance Project Plan](https://docs.google.com/document/d/1L0gqEV3EnyYu4tJELOkVsfA5SEHdEGPb4TeMObLdrRg/edit#heading=h.iiie0sk5j4fd)
- [SCRF - Engagement - Tagging Rules](https://docs.google.com/document/d/1m7XZ6jGk2lHCQNb6HUwWZVVillD4-f3rsLJcbhb4KtU/edit#heading=h.ord54r83vyh)

**Comment by zubepaul** [comment]
Take the List from November 11 Meeting notes in the Project Plan doc above and brainstorm subtasks, create tickets for those subtasks.

**Comment by zubepaul** [comment]
Tagging rules document updated by the moderation team to include in the Forum Maintenance plan

**Comment by encore9870** [comment]
Tracked in smartcontractresearchforum/core-projects#31 now.
