### ISSUE TITLE
Project: Create event ops structure 

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#205]
### Project Description

* The goal of this project is to get the necessary operational structure around event planning

### Work Plan

- [x] create ticket
- [x] draft an event planning overview spreadsheet
- [x] create a template for pitching an event
- [x] create a template for refining the event process 
- [x] create a template to plan the day of the event
- [ ] fill out for the current slate of event
- [ ] socialize this new process with the events team to make sure the relevant docs are filled out

This ticket will stay open until the process is laid out and the next ticket will focus on executing and updating the event strategy 

### Resources

- [link to project plan](https://docs.google.com/document/d/1r0cz5M0d2WQ25UfZJCY8UzFR6amRLooLlOSX0PbnehA/edit?usp=sharing)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by eleventh19** [comment]
- [Event Planning Overview Sheet](https://docs.google.com/spreadsheets/d/1FkSrNWpkSlEKHgN-8go8JU_6l59fWQVyLTIpva7Jv5g/edit?usp=sharing) - this sheet has a list of events and links to other relevant documents 
- [Event pitch template](https://docs.google.com/document/d/1rrme3x7iTeayT31fCvWWJpEtnn2JjAH28-W7PH2zfOk/edit?usp=sharing) - after bringing up an event and generally proposing the idea of a new event, make a copy of this document, fill it out, and then pitch it in more detail to the event team
- [Event planning doc](https://docs.google.com/document/d/1gwsf2EwlYe74YrcKsYAhf4D2SFcPTXM253nBkYw_HnQ/edit#) - once the event pitch doc is approved, fill out this document and iterate on it until you're ready to plan the full run of show
- [Event planning sheet](https://docs.google.com/spreadsheets/d/1apQ0gTJ3mj7ZFnIPMrJRwLYuW7GbOboskR2n4Jqk2qQ/edit?usp=sharing) - once the planning doc was reviewed and approved, then fill out the planning sheet to plan the full outreach and the day of the event itself

Let me know if there are any ideas for what else can be added to improve the planning process as we get ready for events

**Comment by eleventh19** [comment]
Not sure these are actually the most useful for events. We are also mostly focusing on joint events with other groups, which ends up leading to using other tools. Will coordinate with @marvino3 to create an events calendar to make sure it's linked to socials and discovery/outreach more broadly

**Comment by eleventh19** [comment]
Circling back on this and going to create a board to track this

**Comment by encore9870** [comment]
Events board is here: https://github.com/orgs/smartcontractresearchforum/projects/35/views/1. Shall close this issue?
