### ISSUE TITLE
Project: Primary Author Outreach

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_team#206]
### Project Description
This is a proof-of-concept, an experiment to connect with primary authors of the most recent top research papers. We would invite them to publish research summaries of their work on the forum and have an AMA with the community.

### Work Plan
- [x] Phase One: Select research papers targeted for outreach
- [x] Phase Two: Populate spread sheet, fill out message template, send with work email
- [x] Phase Three: Onboarding primary authors
- [x] Phase Four: Content Review
- [x] Phase Five: Publication & AMA
- [x] Phase Six: Payment
- [ ] Phase Seven: Impact Award Flagging

### Resources
[Research Improvement Proposal: Primary Author Outreach (PoC)](https://docs.google.com/document/d/1GrBTv43l5doaPiTaPXGhSOSn0LTNNUPVfWp-8bL9Sm4/edit#)
[SCRF: Process - Primary Author Outreach](https://docs.google.com/document/d/1OHADxJsij04MtyRiN8kq6s-1Clv0MBwBDeb4rFAYFts/edit#heading=h.hx4ss3adaomk)
[RP Reference List (Primary Author Outreach)](https://docs.google.com/spreadsheets/d/1z5ak8xp_cfi13UIEmAtk8VC1GokOwH98DSDHqG7dyiY/edit#gid=711580712)

### Ideas
- send out as soon as RP comes out
- engagement strategy before they see us

**Comment by encore9870** [comment]
Feb 17 sent out A11, A16, A13, A11. Got A11, A16 to reply. Received A16 onboarding contract on Friday (Feb 25)

**Comment by encore9870** [comment]
Feb 22 sent out A06, A17, A03, A05. No response yet.

**Comment by encore9870** [comment]
Feb 27 sent out A12, A18, A19, A20, A04, A07, A21, A02, A08, A09, A10 (2 hours ago)

**Comment by eleventh19** [comment]
Should we close this issue at this point? Feels like a number of folks have been run through it and more outreach is happening. Let me know if there's a different milestone you're shooting for

**Comment by encore9870** [comment]
This is now tracked in smartcontractresearchforum/core-projects#2
