### ISSUE TITLE
Project: SourceCred Implementation

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#207]
**Description**
Implement SourceCred tooling for incentivizing forum contributions.
**Tasks**
- [x] SourceCred doc review to be completed by February 15 2022
- [x] Break Out meeting to discuss questions, concerns, and implementation with Rich, Paul, and Brian
- [x] Prepare presentation and meta forum post for community input
- [x] Meta post no later than Februrary 25 2022
- [x] Tentative date for implementation March 2022
**Materials**
- [Proposal Doc](https://docs.google.com/document/d/1FlcalkkQ5zpsC7c0S3D5EJWrVwsnX7tFztmjjbpJCD8/edit#heading=h.lh0p0mqkmv4t)
- [SourceCred Page](https://sourcecred.io/)

**Comment by zubepaul** [comment]
Deadlines updated:
- Meta post Tuesday, March 1. To be reviewed by @ghettodev and 
- 2nd Week of March is implementation on SCRF Forum

**Comment by zubepaul** [comment]
[Meta post draft](https://docs.google.com/document/d/16LZzre2BmNbE2gPoz7ryx29tTjg5ZWsVxmVIwXtSTH0/edit) updated.

**Comment by zubepaul** [comment]
Meta post draft further updated. Posted to forum on March 2, 2022. Should be discussed in upcoming community calls. @eleventh19 @ghettodev

**Comment by SirAh0** [comment]
Spent weekend generating SourceCred Graphs via Discourse plugin to load SCRF forum data. Able to modify node and edge weight values. Successful testing up until the point of uploading the graph to GitHub and setting up the Github Pages / Actions.

**Comment by zubepaul** [comment]
Updated project plan in the [Proposal Doc](https://docs.google.com/document/d/1FlcalkkQ5zpsC7c0S3D5EJWrVwsnX7tFztmjjbpJCD8/edit#heading=h.lh0p0mqkmv4t)

**Comment by zubepaul** [comment]
Timeline updated in proposal doc @ghettodev

**Comment by zubepaul** [comment]
Create Launch Day plan and process. See project plan.

**Comment by SirAh0** [comment]
Here is the issue tracking the poll and SourceCred launch
https://github.com/smartcontractresearchforum/research_team/issues/235

**Comment by SirAh0** [comment]
launched
