### ISSUE TITLE
Project: Updating the Tools We are Using to Run the Content Pipeline

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_team#212]
### Project Description

As a organization that resides in the digital world, tools that we use are critical to our productivity. This is an opportunity to review the tools and resolve several inconveniences.

### Work Plan

- [ ] Step 1: Improve Github Setting
- [ ] Step 2: Improve Google Docs Settings / How we use it / integrate with #209 
- [ ] Step 3: Exploring New Tools

### Resources

[content pipeline](https://github.com/orgs/smartcontractresearchforum/projects/5)
