### ISSUE TITLE
Project: Open Peer Review Experiment 

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#214]
### Project Description

The goal of this project is to explore what an open peer review for independent researchers experiment can look like. This project will entail:

- Identifying independent researchers who want open peer review
- Creating an advisory board to provide input on the experiment 
- Picking what tools to use for version controlled knowledge management 
- Creating a project plan for the initial researchers 
- Finding peer reviewers for the researchers 
- Running the experiment 

### Work Plan

- [ ] meet on 3/14 to discuss the project with the team 
- [ ] create an initial plan - what is being researcher, next steps for this week, next meetings
- [ ] pull together a few peer review processes
- [ ] start drafting a v1 SCRF Open Peer Review Process doc 
- [ ] share with the core ops team 
- [ ] get advisors onboard 
- [ ] discuss with advisors 
- [ ] refine process
- [ ] find up to 3 independent researchers who want to opt into getting open peer review
- [ ] find 3-6 reviewers depending on the complexity/necessity of interdisciplinary backgrounds 
- [ ] figure out relevant grants 
- [ ] pick tech to use 
- [ ] run trial review with tech 
- [ ] get everyone onboard with the plan 
- [ ] plan start date 
- [ ] start project
- [ ] run open peer review 1
- [ ] run open peer review 2
- [ ] run open peer review 3
- [ ] get final results published on the forum
- [ ] post mortem with researchers
- [ ] post mortem with reviewers
- [ ] post mortem with advisors
- [ ] plan next step
- [ ] close ticket and start new one 

### Resources

- [link to project plan](https://docs.google.com/document/d/1jZSsY8QqS8HJBApXMzTGMtkKs6B5vstECIWpFMOg5io/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

**Comment by eleventh19** [comment]
we met as a group on Monday, created a DM group for the project team to keep the conversation going. next steps are looking into various open peer review projects so that we can come up with what we mean by open and what basic process we want to use for peer review.

**Comment by eleventh19** [comment]
links we've come across so far. still gathering more info on peer review so if you know of any good research/studies/etc, please add here! we'll be working on a notable works in peer review and will explore adding any of the links we have here 

What do we mean by open peer review? 
- https://plos.org/published-peer-review-history/
- https://f1000research.com/articles/6-588 
What documentation can we get on peer review processes?
- Ants Review - [linktree](https://linktr.ee/antsreview), [pre-print](https://arxiv.org/pdf/2101.09378.pdf)
- Presentation, results from a systematic survey of the issues in peer review - [link](https://www.cs.cmu.edu/~nihars/tutorials/Shah_Tutorial_PeerReview_2021.pdf)
- Peer review of articles (not posters, slides or documents) published in F1000Research takes place after publication; once the article is published, expert reviewers (who are suggested primarily by the authors) are formally invited to review. The peer review is administered on behalf of the authors by the F1000Research editorial team, and authors are asked not to contact the reviewers directly. The peer review process is entirely open and transparent: each peer review report, plus the approval status selected by the reviewer, is published with the reviewer's name and affiliation alongside the article. Peer review reports are published after a quick editorial check and the peer review status of the article is updated with every published report. - [link](https://f1000research.com/about)
- https://rescience.github.io/edit/ - github based 
- https://scipost.org/submissions/refereeing_procedure
- http://www.semantic-web-journal.net/reviewers#review
a link that Darren from Atoms passed along:
- https://asapbio.org/crowd-preprint-review

**Comment by nicklinck** [comment]
We have been thinking abstractly about the purpose of peer review in order to determine how to best implement peer review. We have outlined the steps of peer review that we need to address and have been documenting how those steps should be implemented. As well as capturing notes about other efforts to do open peer review.

Details can be found in [https://coda.io/d/SCRF_dzwS_nzx9Lj/Basic-Overview-of-Process_sutl6#_lupt-](our Coda) 

The steps of the peer review process that we have identified are:
1. Researchers to be peer reviewed are selected 
2. Research is conducted (will not be addressed in our MVP) 
3. Research is made available to be peer reviewed
4. Peer reviewers are selected
5. Peer review occurs
6. Reviewed researcher looks at feedback 
7. Reviewed researcher chooses to integrate, ignore, or refute the feedback
8. Reviewer is rewarded
9. Research is disseminated
10. We receive feedback about Reviewers and Researcher’s experience

**Comment by eleventh19** [comment]
We are also doing a community call swap with ResearchHub this week. We joined their call on Monday and they will join our call this Thursday. Also, with the help of Cent at Metagov, got the call info shared with their community

**Comment by Coinproz** [comment]
this study examines how transparency of identity affects perception within a learning environment:
https://www.frontiersin.org/articles/10.3389/feduc.2019.00129/full

**Comment by Coinproz** [comment]
"Strengthening, Hiding or Relinquishing Ethnic Identity in Response to Threat: Implications for Intercultural Relations"
https://www-s3-live.kent.edu/s3fs-root/s3fs-public/file/09-Rosita-Albert-Adina-Schneeweis-Iva-Knobbe.pdf

**Comment by ufkhan97** [comment]
We have written a [proposed flow](https://docs.google.com/document/d/1eZCWuoc_z6Wh3JABEqhsuWF0RxgPxdOV6VK5auPZN-I/edit?usp=sharing) for the peer review process. We have focused on discussing and refining issues of transparency, payment, and tooling. We are looking into different ways we could ensure good data collection that will allow us to develop this process intelligently across iterations.

**Comment by ufkhan97** [comment]
> adding articles to support why having some level of pseudonymity may encourage participation by demographics that feel their identities may threaten the perception of their work unfairly: in other words, **does "transparency" necessitate the publicizing of all identities or is there a viable alternative that does not compromise the integrity of the transparency while still maintaining some level of occlusion for a peer reviewer's identity?**

This a great framing of the question. Allowing the reviewer to maintain some privacy while also ensuring there are no ethical conflicts is a challenge normally handled by a trusted third-party (journal editors) but in lieu of taking on an editorial role, there are important questions about if we could do something like this by replacing a trusted third party with cryptographic proofs. I look forward to digging into if/how this is possible

**Comment by ufkhan97** [comment]
This week we met with Nihar Shah from CMU and were able to ask questions + get feedback on our peer review process. We dug deeper into the literature around peer review and refined the questionnaire for reviewers and authors as well as our final survey. 

We set an intention to be diligent about collecting data and releasing publicly. We hope others will also be able to use the data to uncover insights.

**Comment by ufkhan97** [comment]
Last week, we did a community call where we shared our initial draft of the project and received valuable community feedback. We are very grateful to our community for taking the time to share their ideas for us and we realized we had a need for more feedback. https://www.youtube.com/watch?v=kbVtu3Yshsk 

This week, we drafted documents to share with the community to request online engagement and feedback on the forum. https://docs.google.com/document/d/1Poyw3LFmjGmM5pMyEvtLU7Gp9rOsTNcsegh3DkLSi7o/edit

**Comment by nicklinck** [comment]
This week we are reaching out to researchers who are looking for peer review so that we will have research papers that can be reviewed. 

We are working on the meta post that will give context for individuals who are just learning about our peer review process: [https://docs.google.com/document/d/1Poyw3LFmjGmM5pMyEvtLU7Gp9rOsTNcsegh3DkLSi7o/edit](https://docs.google.com/document/d/1Poyw3LFmjGmM5pMyEvtLU7Gp9rOsTNcsegh3DkLSi7o/edit)

Part of the meta post includes our "Open Questions in Peer Review" which should hopefully get a discussion around our central questions. [https://docs.google.com/document/d/14zH9f6sL_1EKd4HMkR3tevJogabTCniIBEo-K4P0pWc/edit](https://docs.google.com/document/d/14zH9f6sL_1EKd4HMkR3tevJogabTCniIBEo-K4P0pWc/edit)

**Comment by eleventh19** [comment]
We have one potential candidate and I'm reaching out to a few others in terms of who will get the review. Hoping to have more clarity here by the end of next week.

Also, want to link to some relevant videos from our YouTube:

- [4/28/22 extended community call](https://www.youtube.com/watch?v=kbVtu3Yshsk) - Nick and Umar presenting on the proposed open peer review process, featuring a number of other peer review projects)
- [5/12/22 community call - Decentralized Research Centers](https://www.youtube.com/watch?v=1T3dNfbAYus) 
- [5/19/22 community call - discussion on peer review](https://www.youtube.com/watch?v=pmTkPVnxZLY)

**Comment by eleventh19** [comment]
Reached out to the first three potential folks, 2 maybes and a no. Need to think of another person to ask for getting review and then onto finding reviewers.

**Comment by Coinproz** [comment]
an example of an "open-access, peer-reviewed journal" that has legitimately exorbitant application fees for submitting an article with no transparency about whether the fees go to reviewers or not:
https://blockchainhealthcaretoday.com/index.php/journal/about/submissions
"BHTY’s Article Processing Charge (APC) for the international specialty journal is $1450.00 USD for original research articles, $1650.00 USD for Special Reports (15,000 words and upwards of 100 references), and $800.00 USD for students currently enrolled at an academic institution. Please plan accordingly. THERE IS NO FEE FOR BLOGS.

BHTY is pleased to offer authors the option of paying their APC with digital currency (Bitcoin). Contact the publisher for more information if you would like to use this payment method at t.cenaj@partnersindigitalhealth.com

If changes are required post publication, the author(s) will be charged a flat $350.00 USD for revision(s)."

**Comment by eleventh19** [comment]
> an example of an "open-access, peer-reviewed journal" that has legitimately exorbitant application fees for submitting an article with no transparency about whether the fees go to reviewers or not: https://blockchainhealthcaretoday.com/index.php/journal/about/submissions "BHTY’s Article Processing Charge (APC) for the international specialty journal is $1450.00 USD for original research articles, $1650.00 USD for Special Reports (15,000 words and upwards of 100 references), and $800.00 USD for students currently enrolled at an academic institution. Please plan accordingly. THERE IS NO FEE FOR BLOGS.
> 
> BHTY is pleased to offer authors the option of paying their APC with digital currency (Bitcoin). Contact the publisher for more information if you would like to use this payment method at [t.cenaj@partnersindigitalhealth.com](mailto:t.cenaj@partnersindigitalhealth.com)
> 
> If changes are required post publication, the author(s) will be charged a flat $350.00 USD for revision(s)."
> 
> https://blockchainhealthcaretoday.com/index.php/journal/authors-journal in their statement of process, there is no clarification on whether or not reviewers are paid.

Thanks for sharing. That's good for us to know as we start putting together different resources for peer review. 

The team met today and @isss111 joined us. I am following up with more of my outreach in trying to line up the first projects to review.

**Comment by eleventh19** [comment]
Here is the current state of the [knowledge repo](https://coda.io/d/SCRF_dzwS_nzx9Lj/Collective-Knowledge-of-Peer-Review_suvGd#_lu9bZ)

**Comment by nicklinck** [comment]
In order to clean up our knowledge repo, I moved some old pages to: [A coda doc called "Prior Work at SCRF"](https://coda.io/d/Untitled_dnteGF31zjx/Peer-Review-Process_sudqa#_luGku) 

The cleaned up version of the knowledge repo still exists here: [A coda doc called "Peer Review Knowledge Repo"](https://coda.io/d/SCRF_dzwS_nzx9Lj/Peer-Review-Knowledge-Repo_suvGd#_luVG3)

**Comment by ufkhan97** [comment]
Last week, thanks to @eleventh19 and @nicklinck we locked down our first four reviewers! 

We also started modifying our plans to more rapidly move toward running the experiment. 

We're working on documentation and timelining this week as well as identifying further papers and reviewers

**Comment by ufkhan97** [comment]
Last week, we drafted interview questions for participants, started identifying participants for the next round, and created multiple potential project timelines
