### ISSUE TITLE
Project: Project Github

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_team#215]
### Project Description

Github is not only a place for tracking and document running projects at SCRF, but also sits at the core of establishing legitimacy.

This project will revisit how well we are at achieving this objective, and what to do where we are not. 

It is also on the books to renovate the current design to make this tool match our latest needs.

### Work Plan
- [x] Stakeholder meeting (Before March 24)
- [x] Write RIP
- [x] Set up Test Repo
- [x] Running MVPs/Testing/Learning features/Iterations

### Resources
A project plan by Brian: [GitHub Project Management - Project Plan](https://docs.google.com/document/d/1Fw_NMR69jvwS-qqkWrPcRPwWUYOGnl3JscFQDqKBLyY/edit?usp=sharing)

[Github Access Configuration](https://docs.google.com/document/d/1g5w9AI19MBeiHWbYGv197-2nzpqzaRmPmbRdXIjFn4U/edit#heading=h.bzgvv9g4z283)

[Link to Calendar](https://calendar.google.com/calendar/embed?src=c_o03davg4b51lae2tfe0cmv5ojo%40group.calendar.google.com)

**Comment by Coinproz** [comment]
we should be able to leverage the daily pulse from the github board to streamline access to most recent github activity:
https://github.com/smartcontractresearchforum/research_content/pulse/daily

**Comment by ghettodev** [comment]
Here is a [link](https://docs.google.com/document/d/1mabiEvt8xtxy9tOWfIb4RY5DM9cW1T2p74Pi7NEuvUQ/edit#) to the doc for GitHub requirements gathering that can get merged into the user stories.

**Comment by encore9870** [comment]
The meeting today clarified the direction of the RIP. I'll link to the draft once it's ready for review.

**Comment by encore9870** [comment]
A[ first draft](https://docs.google.com/document/d/1izc1MXxAsAZFEuuY6XL-wlWNzwAcc1WCl96NzOHGBEg/edit#) of the RIP.

**Comment by encore9870** [comment]
I've updated the ticket to include a link to a calendar that keeps track of relevant meetings (starting form the last group meeting) or task planning. Otherwise this ticket will be updated when we hit a new milestone.

**Comment by encore9870** [comment]
We got together and reviewed a version of Github access configuration on April 27, 2022. Our next deliverable would be to launch an instance and use it for project management. This is not blocked.

**Comment by encore9870** [comment]
We're tracking it here now smartcontractresearchforum/core-projects#3
