### ISSUE TITLE
Project: CRM Software

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#225]
### Project Description

We've been talking about the idea of CRM software for a while and are finally looking into it. I haven't had a chance to write up a project plan for this yet. I had a call with someone from Hubspot last week and someone from Raklet 2 weeks ago (not really CRM so not right). 

In the hubspot call, I gave a download of some of the main requirements so they're pitching us solutions in the upcoming call this Fri. 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] call this Fri with hubspot rep to discuss how their tool can help us 
- [x] review with core ops team
- [x] do we want to do any more work exploring? if yes, who is doing it?
- [x] set up account with hubspot if we choose to go with them
- [ ] hire a hubspot consultant to help get it set up and configured 

### Resources

- Need project plan
- [Miro board](https://miro.com/app/board/uXjVOBRsJg4=/) with stages of outreach mapped out

**Comment by eleventh19** [comment]
Closing this out as we've chosen a CRM
