### ISSUE TITLE
Project: 

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/research_team#230]
### Commenting Guide [for Forum]

This guide spells out why and how to make posts on the forum and it includes examples of comments, engagement team contact information and is planned to live somewhere publicly - Github?  where new community members could easily access.  

### Work Plan
- [ ] Review and get approval Guide language
- [ ] Decide where to post
- [ ] (Engagement) Make a monthly announcement on Discord with link to document 

### Resources
- https://docs.google.com/document/d/1iQvHNghwItxL9V0othYSONVlgHVR0tw-StHGm9CbHco/edit#heading=h.lalhvwdbwr3
