### ISSUE TITLE
Project: Community Call Agenda Creation

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#243]
## Description
A project to create, disseminate, and get community input on the Community Call Agenda
### Tasks
- [ ] Create and maintain Community Call agenda
- [ ] Create process to interface with Discovery
- [ ] Create mechanism and process to allow community input on Community Call agenda
### Resources
- [Project Proposal](https://docs.google.com/document/d/1ccp_1Vx4gqqKF_AxO_VSHI_6o7M0meYx6M165kKTCkg/edit#)

**Comment by encore9870** [comment]
Weekly guild agenda tracked on https://github.com/orgs/smartcontractresearchforum/projects/31
