### ISSUE TITLE
Project: CRM Setup

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#249]
### Project Description

This card is to track the order, initial setup, onboarding, and full setup of the CRM tool (Hubspot). As of June 1st, the CRM has been ordered and I added a single contact. 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] order CRM
- [ ] Set up onboarding call
- [ ] go through initial onboarding (60 days)
- [ ] import contacts from outreach sheet
- [ ] integrate to calendar
- [ ] integrate to email
- [ ] add all active outreach
- [ ] anything else for the initial setup?

This issue can be closed once Hubspot is setup

### Resources

This is building on the [CRM project proposal](https://docs.google.com/document/d/1NswH57L-v4g829BMINcbtGDGWiuY836QCStOBqAiKKM/edit#). No project doc for this project yet
