### ISSUE TITLE
Project: Peer Review Knowledge Repo's

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#250]
### Project Description

The [Peer Review project](https://github.com/smartcontractresearchforum/research_team/issues/214) is expanding and now has two other components, one of which is building knowledge repo's relevant to peer review. This will include overviews of projects, resources, research, etc.

### Work Plan

The first step is going to be to draft a potential list of repo's. From there, we will have to evaluate if it makes sense to accomplish certain ones before starting to work on multiple (say putting together a map of projects and of tooling options while starting to draft the list of open problems, etc.) 

- [x] mention the idea to the team 
- [ ] build out an initial list of potential repo's
- [ ] create a proposed plan of action from there - to be updated in the comments 

### Resources

- [Project proposal](https://docs.google.com/document/d/1jZSsY8QqS8HJBApXMzTGMtkKs6B5vstECIWpFMOg5io/edit#)
- [Process](https://docs.google.com/document/u/1/d/1eZCWuoc_z6Wh3JABEqhsuWF0RxgPxdOV6VK5auPZN-I/edit)
- All other docs put together for the experiment can be [found here](https://github.com/smartcontractresearchforum/research_team/issues/214).
