### ISSUE TITLE
Project: Peer Review Community

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#251]
### Project Description

This ticket is meant to detail the project of planning initial community as it pertains to the [open peer review experiment](https://github.com/smartcontractresearchforum/research_team/issues/214). The community has two portions to it: community amongst those actively working on peer review research/projects and general community pertaining to open peer review. 

### Work Plan

Proposed steps:
- [x] map the projects at the intersection of web3 + peer review
- [ ] reach out to the projects to suggest a virtual convening 
- [ ] plan what the convening could look like, need to have a bias for action 
- [ ] joint CRM to do joint outreach to meta-researchers?
- [ ] what is the SCRF plan for meta-researcher outreach? 
- [ ] an event or convening for meta-researchers (Boston?)

### Resources

Check [this ticket](https://github.com/smartcontractresearchforum/research_team/issues/214) for all relevant info on the open review experiment and [this ticket](https://github.com/smartcontractresearchforum/research_team/issues/250) for any work relating to the peer review knowledge repo's.

**Comment by eleventh19** [comment]
getting the first call scheduled in early July. currently, contributors from 6/9 peer review+web3 projects accepted the invite
