### ISSUE TITLE
Project: Board to track potential hires

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#252]
### Project Description

This issue is to track the development of a board dedicated to hiring needs. This board would be the place new roles are proposed and tracked. 

### Work Plan

- [ ] reach out to Brian and Twan
- [ ] talk about the requirements for the board
- [ ] set up a trial
- [ ] make any adjustments
- [ ] close card

### Resources

Related to the [hiring process development issue](https://github.com/smartcontractresearchforum/operations/issues/36).

**Comment by SirAh0** [comment]
Eugene, your schedule is packed. Please feel free to find a time on my calendar and we can get this done if you would like a 1-1. 

Alternatively, we can async chat on discord and get the project rolling. 

If you can get the requirements set then I'm happy to implement this for you.

**Comment by SirAh0** [comment]
@eleventh19  sent you a DM on chat to take next steps.

**Comment by encore9870** [comment]
This had spun into smartcontractresearchforum/research_team#256 and is completed. I believe there's a wider discussion on tracking PII with a secure, dedicated program. I'm going to guess it's put on hold after Tania's OOO and she will be creating a ticket to track that process.
