### ISSUE TITLE
Project: Create New Community Calendar 

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/research_team#253]
### Project Description

**How To Share the Calendar**
Rather than directly linking to the calendar, share this link to the Doc Repo
https://github.com/smartcontractresearchforum/docs/blob/main/en/content_connecting_with_scrf.md#meetings

*closing out the old community calendar here https://calendar.google.com/calendar/u/0/embed?src=c_45nqubmu17kcm9r1p8o5sqtte0@group.calendar.google.com
 
Create new calendar under SCRF.io

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] @eleventh19 close out other calendar
- [ ] @vincenzospaghetti and team create new list of events to be migrated
- [x] @SirAh0 migrates calendar under scrf.io
- [x] #254
- [x] https://github.com/smartcontractresearchforum/discovery/issues/119

### Resources

- [Calendar Project Plan](https://docs.google.com/document/d/1WEW0Unw_X_xtpAAcYpl7NZqbRkhRKgC0PYN4sxYpsD8/edit?usp=sharing)
- [Add New Calendar Item](https://github.com/smartcontractresearchforum/discovery/issues/new/choose)
- [Calendar Project Board](https://github.com/orgs/smartcontractresearchforum/projects/30/views/1)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by SirAh0** [comment]
- [x] I will work with @eleventh19 to migrate the calendar to the [SCRF Calendar of Events](https://github.com/orgs/smartcontractresearchforum/projects/30) Project Board 

I've created a new shared google account for SCRF to use to host a calendar. 

Here is the URL for the new calendar. I've also updated the Project Plan with this link.
https://calendar.google.com/calendar/u/0?cid=bnVsbEBzY3JmLmlv

**Comment by vincenzospaghetti** [comment]
Need to update community on new process:

- [ ] Create supporting document 'how-to' on how folks should submit a new calendar invite
- [ ] Roll out with communication on Discord

**Comment by SirAh0** [comment]
Please ensure when sharing the calendar link to use this URL

SCRF Community Meetings
https://github.com/smartcontractresearchforum/docs/blob/main/en/content_connecting_with_scrf.md#meetings

**Comment by SirAh0** [comment]
New Calendar items can be submitted here
https://github.com/smartcontractresearchforum/discovery/issues/new/choose

**Comment by encore9870** [comment]
This is very, very, done. Good progress!
