### ISSUE TITLE
Project: DRC Content to Present

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#255]
### Project Description

This is a project coordinating with Maria and Matt in Discovery to present on Decentralized Research Centers to be able to present at public presentations. 

### Work Plan

- [x] mention the general project to Maria and Matt
- [x] create an updated presentation 
- [x] review with Rich
- [x] review with Maria and Matt
- [x] get a draft 
- [x] revisions
- [x] present on June 20th
- [x] review and revise

### Resources

[Presentation draft](https://discord.com/channels/@me/832968981383086080/983909037747875920) on SCRF & DRCs

**Comment by marvino3** [comment]
[Updated DRC Presentation](https://docs.google.com/presentation/d/1kyi3Jdm8WD5Y6ooyYX1gttcos-Et2HI4V7l3HvKAoaU/edit?usp=sharing)

**Comment by eleventh19** [comment]
Closing this out as we were able to get this created and this is the version I use for presenting. Will open a new issue if/when we need to go through revisions
