### ISSUE TITLE
Project: Update TOS with DMCA Terms

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/research_team#257]
### Project Description

*Adding DCMA language to TOS

https://www.smartcontractresearch.org/tos

### Work Plan

- [ ] See language document for TOS here: https://docs.google.com/document/d/1mmIdnnWvWlOavCzP9OW_fv_UQkjI0k8TCO1q2HS_1LY/edit?usp=sharing 
- [ ] Create Google Voice number for Eugene
- [ ] Add Google Voice number to language document 
- [ ] @SirAh0 Update TOS

### Resources

- https://docs.google.com/document/d/1mmIdnnWvWlOavCzP9OW_fv_UQkjI0k8TCO1q2HS_1LY/edit?usp=sharing)

People Involved:
- @eleventh19 
- @ghettodev

**Comment by SirAh0** [comment]
> @SirAh0 Update TOS

Where should the TOS be updated?

**Comment by vincenzospaghetti** [comment]
https://www.smartcontractresearch.org/tos

**Comment by SirAh0** [comment]
OK - Please let me know when the document is ready and I will add the **Copyright, the DCMA & Takedowns** section. You can simply assign me to this issue once it is ready thank you!

**Comment by vincenzospaghetti** [comment]
@SirAh0 can you help @eleventh19 create a google voice number? That is the only other thing we are waiting on before posting.

**Comment by SirAh0** [comment]
> @SirAh0 can you help @eleventh19 create a google voice number? That is the only other thing we are waiting on before posting.

https://github.com/smartcontractresearchforum/IT/issues/11

I've created an issue for that in the IT Repo. I'll let you know when that is setup.

**Comment by SirAh0** [comment]
Google voice should be provisioned for @eleventh19 waiting for him to confirm.

**Comment by vincenzospaghetti** [comment]
@SirAh0 We are waiting on signoff from an external legal team on the language for this. Hold until we have that. I will update the ticket here.

@eleventh19 @ghettodev

**Comment by SirAh0** [comment]
Understood, Eugene mentioned gvoice wasn't activated for some reason. I'll try and find out what's going on.

**Comment by vincenzospaghetti** [comment]
New language from lawyers: https://docs.google.com/document/d/1OpWlwkBy2ITFzCBXCKpanSatogkWNWel/edit?usp=sharing&ouid=100531522375056628626&rtpof=true&sd=true

Need final sign off - will update when cleared.
