### ISSUE TITLE
Project: Community Hub at DevCon VI

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#260]
### Project Description

I want to propose SCRF coordinating a Research Community Hub at Devcon VI. For this year's event, the team created an RFP for community hubs - [see here](https://forum.devcon.org/t/rfp-5-community-hubs/454) for the RFP. I think it makes a lot of sense for SCRF to organize one as we can bring together a variety of industry and academic players to have a mix of research events/discussions. 

I put out some tentative feelers and I think we can partner with groups like BlockScience, Metagov, DAO Research Collective, TEC, and others. 

### Work Plan

- [ ] create this card
- [ ] share the RFP with teammates 
- [ ] start a write up on addressing q's in the RFP
- [ ] start a project plan
- [ ] complete both of the above and share with core ops 
- [ ] commence planning 

### Resources

- [link to project plan](https://docs.google.com/document/d/1BC4uG4Bnwq1Gz56fzedV8o3Wb58-KJRTN3cV1-99nSo/edit#)
- [link to the specific RFP responses](https://docs.google.com/document/d/19nY9042JSI68S4CL5GdECRgQTahVa31HJ-DdU0VVP1w/edit)

**Comment by eleventh19** [comment]
Long story short, the space is much smaller than imagined. Not sure what we're going to do now. Messaging with Angela to figure out our plan of action
