### ISSUE TITLE
Project: Create Press Packs (Kits) 

### ISSUE THREAD

**Issue by ghettodev** [smartcontractresearchforum/research_team#3]
### Project Description

Package of documents describing the benefits of SCRF for outsiders.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [ ] Coordinate with engagement team to determine target audience, messaging, approach
- [ ] Collate existing materials
- [ ] Identify and create missing materials
- [ ] Update out-of-date materials
- [ ] Create packets
- [ ] Share with Engagement Team / Rich
- [ ] Incorporate feedback
- [ ] Copyediting
- [ ] Create PDFs
- [ ] Periodic updates (adding details of new features)

### Resources

- [link to project plan](https://docs.google.com/document/d/1cJinzz8sTftWxoVJY8bGqmY1W6FR1TWBMdlJ-lEzDkw/edit)
- [link to process doc/proof of concept](https://docs.google.com/document/d/1iuPirU21LuBpsb5p-9OJW0WDQQtp6kW_CNLxy5lfbME/edit#)
- [link to any other relevant supporting materials]

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by ghettodev** [comment]
@jamesmcgirk tagging you on this one

**Comment by ghettodev** [comment]
- the presspack should include a howto to create the forum post they are linking to.

**Comment by ghettodev** [comment]
Work in progress is here: 

https://docs.google.com/document/d/1jNYj09wOLfbqBgu_5mYrsPUQVSeY4qt8CnqGLcjZ3rM/edit#heading=h.lw3nhvpvo9pc

**Comment by ghettodev** [comment]
Would love to see a one page description about what the project plan is here.

**Comment by jamesmcgirk** [comment]
https://docs.google.com/document/d/1cJinzz8sTftWxoVJY8bGqmY1W6FR1TWBMdlJ-lEzDkw/edit#heading=h.h50zkyeuvm32

**Comment by jamesmcgirk** [comment]
moving to the icebox as there's an existing ticket encompassing this

**Comment by jamesmcgirk** [comment]
Old material:

- Links to Digital Resources (branding elements, 2 sentence overview)
- Link to PDF one pager
- Example blurb to link back to SCRF "Please join the discussion about this post on SCRF..."
- Explanation of value we provide by moderating their discussions
- Why people should share their content on our forum, what they can get out of it, etc

**Comment by jamesmcgirk** [comment]
@jamesmcgirk update the links when you complete the process doc

**Comment by jamesmcgirk** [comment]
I'm going to move this one to complete. (Discovery Kits duplicates this)

**Comment by encore9870** [comment]
The responsibilities mentioned in this ticket are now shared by discovery and engagement teams. 

Discovery is working on 
- documentation (for internal knowledge)
- scrf.io website (showcasing why we are great)
- socials (pushing all the good stuff to the world to see us). 

Engagement owns 
- onboarding (pointing new people towards the correct opportunities)
- chat and the forum (putting relevant information for the community to see)
