### ISSUE TITLE
Content Engagement Workflow

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#35]
### Project Description

Creating an engagement workflow.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

Engagement Workflow

- [x] Create Go to Market template
- [x] Define GtM / Publishing Process connection
- [x] Define Engagement Workflow
- [ ] Refine as needed
- [ ] Capture analytics

Moderation Playbook

- [x] Create 
- [x] Get notifications for new posts
- [x] Assign owners for post engagements
- [ ] Define SLAs for post triage (24hrs & red, green, yellow,thumb)
- [ ] Define SLAs for post responses/review

### Resources

- [Go to Market tracking spreadsheet](https://docs.google.com/spreadsheets/d/1OAhoXcCd2kuwxvU4TibUTB-klTKtd92vcKtGTL_8Lvk/edit#gid=0)
- [SCRF Moderation Team Process](https://docs.google.com/document/d/1pg8onW7IXj0rs3xSH00vPptg4_QafU7uO3rRNkueAG8/edit#heading=h.vn9az7d7nx7n)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
Here's a very skeletal first draft. Please feel free to add: https://docs.google.com/document/d/1KxzZ1C3ArUgVxlU_vjVPHwVs5uJoQBbdapPv3FFNMi0/edit

**Comment by ghettodev** [comment]
Update this into a new template format.

**Comment by jamesmcgirk** [comment]
@zubepaul presented the new version

**Comment by jamesmcgirk** [comment]
@jamesmcgirk add Eric's template to the ticket

**Comment by zubepaul** [comment]
Drafting "Gold Standard" 2-page GTM with Eugene

**Comment by zubepaul** [comment]
Discuss merging with Content Creation Workflow

**Comment by zubepaul** [comment]
Going to review process for maintenance.

**Comment by zubepaul** [comment]
Need to create a primary author process with an update.

**Comment by eleventh19** [comment]
Need to re-open this as there was some engagement workflow that was getting edited. there are changes to be made to the workflow outlined (e.g. add post ideas)

**Comment by zubepaul** [comment]
Make sure to update the process a little more and make the things that have been captured and that the engagement with members of the community is prioritized. Have a chat with Sam and Ralph with fresh eye frustration.

**Comment by zubepaul** [comment]
Create and include a best practices section or separate doc.

**Comment by zubepaul** [comment]
And then create a centralized document that can be part of all engagement and moderation. Call this the Curation Playbook

**Comment by zubepaul** [comment]
Update this with suggestions, run by Engagement, and then off to the PR team.
