### ISSUE TITLE
Project: Develop Researcher Onboarding Materials

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#38]
### Project Description

Assembling documentation for onboarding new researchers, ensuring that it contains up-to-date information on who does what, where to find docs, and when things should happen.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Consolidate existing onboarding resources
- [x] Interview Research Team to get feedback on onboarding requirements
- [x] Define Researcher roles and responsibilities
- [x] Specify weekly tasks
- [x] Explain the Document pipeline
- [x] Explain Go to Market strategies
- [x] Create welcome deck / onboarding manual (10 slides, 10 minutes)
- [x] Document the onboarding process.
- [x] Get sign off on SCRF: Researcher Onboarding Process
- [x] Present to Research Team
- [x] Finalize and Convert to MD - Mandate: Research Team
- [x] Finalize and Convert to MD - Onboarding - Researcher and Research Fellows
- [x] Finalize and Convert to MD - Research Summary: Template
- [ ] Finalize and Convert to MD - Content Publishing Workflow
- [x] Finalize and Convert to MD - Process: Research Improvement Proposal 

### Resources

- [SCRF: Project Plan - Researcher Onboarding](https://docs.google.com/document/d/1weyQShGk4tZaTUctfEq1UISuoCb6vUxEgzsicMv1qC0/edit#heading=h.8wbm87287w13)
- [SCRF: Researcher Onboarding Process](https://docs.google.com/document/d/1P2KJpp-RdTYz1NOt7ztLHWdW9wMqAUy1Zb3U_65xpow/edit#)
- [SCRF: Onboarding - Research Associates and Fellows](https://docs.google.com/document/d/1oqjfR8Appy7lLGrXHQicYjQ2GEovBKJ6BZqcPMrYfQs/edit#)
- [SCRF: Mandate - Research Team - WIP)](https://docs.google.com/document/d/1qkpj-aHYQ_uHVRYxZUHrQJJu2T6wvNMJDxHp2xXXygw/edit#heading=h.a0m96um2j78v)
- [Research Summary: Template](https://github.com/smartcontractresearchforum/research_content/blob/main/templates/research_summary.md)
- [SCRF: Process - Content Publishing Workflow](https://docs.google.com/document/d/1Dxl4mpLQ01QrSvJC7HAl3xWR92aiIo4QgFwyk9w53Hk/edit)
- [Tracking Document - link not included because it contains personal information]

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by ericjaurena** [comment]
I also got started on this in #24, but closed it. See [my old doc](https://docs.google.com/document/d/15sQ_IyuNHBLyjik0ARxRZyiAfIZJ_wS1z5vdwWKJ7hg/edit#heading=h.kjih8e2wu6r6) and merge any useful content.

**Comment by jamesmcgirk** [comment]
Moving to Icebox as this ticket has been eclipsed by the Onboarding documentation project

**Comment by jamesmcgirk** [comment]
Old wording: [This document](https://docs.google.com/document/d/1EyvVG45Rbk1AMo6YZfZ43UHPxJqF7aLxfihanvEkrZ8/edit?usp=sharing) provides answers to frequently asked questions by new researchers. E.g.:
- How do I get paid?
- What is the workflow for moving a doc from idea -> post?
- Where is work tracked?

This document is intended to lower the operational overhead of onboarding new researchers.

[This](https://docs.google.com/document/d/15sQ_IyuNHBLyjik0ARxRZyiAfIZJ_wS1z5vdwWKJ7hg/edit#heading=h.kjih8e2wu6r6) now deprecated doc contains additional thoughts, and should be merged to James' doc.

**Comment by jamesmcgirk** [comment]
@jamesmcgirk create an onboarding presentation for 3/24

**Comment by ghettodev** [comment]
We're going to need markdown versions of all the docs and presentations. It's probably easier if I make them. Once you have everything signed off on can you assign a ticket to me for the github versions?

**Comment by jamesmcgirk** [comment]
Presenting this on 3/24, next need to update the Onboarding FAQ and other documents with new details

**Comment by jamesmcgirk** [comment]
3/30 - Discussing with Rich

**Comment by jamesmcgirk** [comment]
Updated with documents that need to be converted into markdown. Waiting for payment info from @ghettodev in the FAQ and Onboarding - Researcher and Research Fellows docs, need markdown version of Content Workflow from @visavishesh waiting for team sign off for research mandate

**Comment by jamesmcgirk** [comment]
Update the Content Publishing Workflow and @visavishesh will validate it.

**Comment by jamesmcgirk** [comment]
Removing the redundant Onboarding FAQ.

**Comment by jamesmcgirk** [comment]
@jamesmcgirk review for MD

**Comment by jamesmcgirk** [comment]
@ghettodev [mandate](https://docs.google.com/document/d/1qkpj-aHYQ_uHVRYxZUHrQJJu2T6wvNMJDxHp2xXXygw/edit), [style guide](https://docs.google.com/document/d/1o5GO9cbqgYNpwBM90LGGC7nABWcLl2h4BhShm1MeV50/edit), [Content Workflow Pipeline](https://docs.google.com/document/d/1Dxl4mpLQ01QrSvJC7HAl3xWR92aiIo4QgFwyk9w53Hk/edit#). You mentioned that you'd handle the [Onboarding - Research Fellow and Researcher](https://docs.google.com/document/d/1oqjfR8Appy7lLGrXHQicYjQ2GEovBKJ6BZqcPMrYfQs/edit)

**Comment by ghettodev** [comment]
Cheers, I'll get them started in hackmd, and then we can do a training session with the team.

**Comment by eleventh19** [comment]
@eleventh19 update to reflect a general onboarding ticket

**Comment by jamesmcgirk** [comment]
Check on the content workflow pipeline, convert to MD

**Comment by jamesmcgirk** [comment]
@zubepaul we should probably open another ticket for the rest of the onboarding materials

**Comment by jamesmcgirk** [comment]
Should this be merged with https://github.com/smartcontractresearchforum/research_team/issues/133
