### ISSUE TITLE
Project: SCRF Glossary

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#52]
### Project Description

Standard definitions of blockchain-related terms taken from research summaries. Includes references, synonyms and related terms. This is Phase One of the project. This will produce is a glossary in Github, in markdown that is usable (something we can provide anchor tags to). 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Transfer definitions from Summaries to PoC
- [x] Cleanup
- [x] Create initial pared down list of definitions using content tag list
- [x] Create workflow documentation on how to get new definitions added to the glossary and create a corresponding forum post
- [x] Seek internal consensus on definitions
- [x] Add citations, internal navigation
- [x] Create external reference doc that can be linked to from the forum (markdown) 
- [ ] Incorporate public discussion and feedback into changes and edits to the definitions or sources

### Resources

- [link to project plan](https://docs.google.com/document/d/1t6eg3zgwxh0w-X98sZTSN7rgGWcA5JCBPb1WNEf7zyI/edit#)
- [link to process doc/proof of concept](https://docs.google.com/document/d/1REVZHzQYzryAfrwQo1EUCnDchHZZXoYtaJLeG-S3ZjQ/edit)
- [Glossary PoC](https://docs.google.com/spreadsheets/d/1CM9zboj3P6G15fK81xr8qkplRwf29VSbOb8G2vz2Y54/edit#gid=0)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
@jamesmcgirk to transfer Glossary text into the[ Spreadsheet](https://docs.google.com/spreadsheets/d/1CM9zboj3P6G15fK81xr8qkplRwf29VSbOb8G2vz2Y54/edit#gid=0), next step will be to assign researchers to check and find citations

**Comment by jamesmcgirk** [comment]
Will eventually tie back into the topic taxonomy, have to be careful with maintenance (needs a plan), organization

**Comment by jamesmcgirk** [comment]
Phase One project - the thing this will produce is a glossary in Github, in markdown that is usable (something we can provide anchor tags to)

**Comment by Coinproz** [comment]
Create a path for engagement to establish a pipeline for discussing tags and definitions to be added into the main glossary.  If the community has an opportunity to discuss the merits of a tag or definition, the process of adding to the glossary would be more democratic and by proxy generate engagement.

**Comment by Coinproz** [comment]
Opportunity to use introduction/101 posts to present industry-specific terminology that can be discussed by the community on whether definitions or tags should be adopted into the general smart contract/blockchain lexicon.
