### ISSUE TITLE
SCRF LinkedIn Page

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#53]
### Project Description

Academia is highly engaged with LinkedIn, it would be good to have a presence so we can post forum content. Create an SCRF LinkedIn company page.

### Work Plan

- [x] create linked in account
- [x] populate with brief introductory text
- [x] make introductory post

### Resources

- [SCRF: Social Media Presence Plan WIP](https://docs.google.com/document/d/10o9q1bPOEjULd-XMtbMUVOzjTe50RNamqeDPb_t9Nas/edit#heading=h.ks6kuvnmzzp1)
- [SCRF LinkedIn Page](https://www.linkedin.com/company/smart-contract-research-forum/)

**Comment by jamesmcgirk** [comment]
https://docs.google.com/document/d/1rujAsyam_sqKBKXgZUGbmUwC2Dg2bWKz5WSUhAQsmD4/edit

https://docs.google.com/document/d/1P9K0tMKIGsBZyNjjL5eRW45jfiLwH2pwkPgdAWJlIZc/edit#

**Comment by jamesmcgirk** [comment]
First draft of text complete (see above) - needs Rich and Trent to weigh in.

**Comment by ghettodev** [comment]
updated linkedin header image

**Comment by ghettodev** [comment]
Made first post. Calling this one done.
