### ISSUE TITLE
Process: Researcher Onboarding 

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#56]
### Project Description

The onboarding process is a way for SCRF to teach, socialize, and indoctrinate new researchers into SCRF culture and processes.

### Work Plan

- [x] Consolidate existing resources
- [x] Interview research team
- [x] Define researcher roles and responsibilities
- [x] Specify weekly tasks
- [x] Explain document pipeline
- [x] Explain go to market strategy
- [x] Create welcome deck
- [x] Document the onboarding process
- [x]  Get sign off on researcher onboarding process

### Resources

- [link to project plan](https://docs.google.com/document/d/1weyQShGk4tZaTUctfEq1UISuoCb6vUxEgzsicMv1qC0/edit#heading=h.h7tclgf7d1xl)
- [link to process document / PoC](https://docs.google.com/document/d/1P2KJpp-RdTYz1NOt7ztLHWdW9wMqAUy1Zb3U_65xpow/edit)
 - [link to Onboarding presentation](https://docs.google.com/presentation/d/16CKiR0xkN82Ax5uk9OYS8KWOmW3LHEKK32TB9bSL9ps/edit#slide=id.p)
- [link to Onboarding Spreadsheet](https://docs.google.com/spreadsheets/d/1e-MjEFGD_K4sBkQCraSJeYLwjy3_uJNctPtrzO1f4vI/edit#gid=0)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
Welcome to SCRF! Onboarding Presentation
Research Team Mandate (in progress)
Document Pipeline
Onboarding FAQ  (this document)
Project Implementation Process
Selection Criteria

**Comment by jamesmcgirk** [comment]
Added a column to the onboarding tracking sheet listing referrals
