### ISSUE TITLE
Project: Research Improvement Proposal Implementation

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#63]
### Project Description

SCRF’s culture is based on the open-source software community. Anyone can suggest an improvement or a new process, but it has to fit in the existing framework. Project Proposals are the first step of our Research Improvement Proposal (RIP) process. This is how we decide whether a suggested improvement provides a benefit, whether that benefit is worth the resources spent, and whether or not it makes sense given other projects already in process.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Create framework
- [x] Discuss with Ops team
- [x] Refine framework
- [x] Draft documents
- [x] Present project implementation process
- [x] Post documentation to Github 

### Resources

- [link to process doc/proof of concept](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)
-  [template](https://docs.google.com/document/d/1gIE3CJFBDxV7bduZBha6E1Kvqc8H_aV5tgaxblO60X4/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
The implementation docs are completed, moving to complete. Unclear why this is slugged as Q2, Q3 project.

**Comment by ishgun178** [comment]
Research Improvement Proposal doc and SCRF: Process - Research Improvement Proposal both have been completed added to GitHub.

**Comment by encore9870** [comment]
Closing since it's completed, and a more wider discussion on the general topic is now overseen by the core-pms team.
