### ISSUE TITLE
Project: Developing the One-Pager Content Type

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#65]
### Project Description

One-pagers are a content form designed to facilitate outreach. They provide a rapid, jargon-free, intriguing summary of what the Smart Contract Research Forum is, how being a part of it can benefit the reader, and how he or she can connect.

### Work Plan

- [x] Idea presented to Ops for new one pager content type
- [x] Workflow developed
- [x] Presented to the team
- [x] First Example generated 

### Resources

- [link to project plan](https://docs.google.com/document/d/1jNYj09wOLfbqBgu_5mYrsPUQVSeY4qt8CnqGLcjZ3rM/edit#)
- [link to process doc/proof of concept](https://docs.google.com/document/d/1a2zU0o7s80Sb1_TzRVv-rOCJaJrRCt5hQg3RCFwls0w/edit)
- [link to any other relevant supporting materials](https://docs.google.com/document/d/103I31XeVbkCcjXGvr8DVp18D63FYwUL2RrmlOoHtfrs/edit)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by ishgun178** [comment]
This one-pager has been completed and added to GitHub under the '[Research Associates for Grants](https://github.com/smartcontractresearchforum/docs/blob/main/en/grants_general_contributors.md)' doc.
