### ISSUE TITLE
Project: Develop Researcher Onboarding Process

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#66]
### Project Description

The onboarding process is a way for SCRF to teach, socialize, and indoctrinate new researchers into SCRF culture and processes.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Consolidate existing onboarding resources
- [x] Interview Research Team to get feedback on onboarding requirements
- [x] Define Researcher roles and responsibilities
- [x] Specify weekly tasks
- [x] Explain the Document pipeline
- [x] Explain Go to Market strategies
- [x] Create welcome deck / onboarding manual (10 slides, 10 minutes)
- [x] Document the onboarding process.
- [x] Get sign off on SCRF: Researcher Onboarding Process

### Resources

- [link to project plan](https://docs.google.com/document/d/1weyQShGk4tZaTUctfEq1UISuoCb6vUxEgzsicMv1qC0/edit)
- [link to process doc/proof of concept](https://docs.google.com/document/d/1P2KJpp-RdTYz1NOt7ztLHWdW9wMqAUy1Zb3U_65xpow/edit)
- [link to Onboarding presentation](https://docs.google.com/presentation/d/16CKiR0xkN82Ax5uk9OYS8KWOmW3LHEKK32TB9bSL9ps/edit)
- [link to Onboarding Spreadsheet](https://docs.google.com/spreadsheets/d/1e-MjEFGD_K4sBkQCraSJeYLwjy3_uJNctPtrzO1f4vI/edit#gid=0)
- [Researcher Onboarding](https://docs.google.com/document/d/1oqjfR8Appy7lLGrXHQicYjQ2GEovBKJ6BZqcPMrYfQs/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
@jamesmcgirk update this with the new documents, remove them from the process
