### ISSUE TITLE
Project: Content Selection Framework

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#68]
### Project Description

This is a framework that incorporates the key properties of a body of research work to produce holistic evaluations of content proposals.  
In the content creation workflow, the Research Team lead uses a set of criteria to evaluate and ultimately decide to approve or reject content proposals. In an effort to formalize and communicate these criteria, we have identified the need for a Content Evaluation Framework. 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Develop a POC framework
- [x] Present to S&O team
- [x] Refine based on feedback
- [x] Incorporate into Content Coverage Map and Document Pipeline Process
- [x] Educate Research Team on how to use the framework
- [x] Publish framework
### Resources

- [link to project plan](https://docs.google.com/document/d/1Dv3q2BItDHSz85jbtT64gTHlOJDAVgk7zYgfktL_L2I/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_
