### ISSUE TITLE
Project:  Research Pulse

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#69]
### Project Description

*Research Pulse is a feed of recently-published research papers that have been curated by industry professionals. It’s the RSS feed of high-quality, bleeding-edge industry publications.
Hundreds of papers are published every week on the various technologies that underpin crypto assets. Nevertheless, few publications actually contain novel ideas that push the industry forward. 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Research Pulse relies predominantly on the Google Scholar API for content discovery. 
- [x] 170+ queries tracking key publications/topics/authors are made using organic_results of that day
- [x] The scisbd=1 parameter returns the abstracts of query results, which are then indexed.
- [x] In a single repository, all abstracts are curated and interesting publications are flagged
- [x] A batch of ~10 papers is posted by Lucas on Fridays to the Research Pulse category

### Resources

- [link to project plan](https://docs.google.com/document/d/1gDAJVzOM7V0l5eiVTMTQ6_N-v2cJk-JqQ4ypHPjFfao/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_
