### ISSUE TITLE
Project: Go-to-Market Strategy

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#71]
### Project Description

Outlines the engagement team's workflow during and after the publication of a research summary or other content type.

### Work Plan

- [x] Draft go-to-market strategy 
- [x] Present to Engagement Team
- [ ] Incorporate feedback 
- [ ] Present to Group
- [ ] Incorporate feedback
- [ ] Post markup to Github

### Resources

- [link to process doc/proof of concept](https://docs.google.com/document/d/1pg8onW7IXj0rs3xSH00vPptg4_QafU7uO3rRNkueAG8/edit#heading=h.vn9az7d7nx7n)
- [link to any other relevant supporting materials](#linkme)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
@zubepaul (who needs to be invited to the forum)

**Comment by ghettodev** [comment]
Invite sent
