### ISSUE TITLE
Project Proposal: Researcher Micro-Grants Program

### ISSUE THREAD

**Issue by ghettodev** [smartcontractresearchforum/research_team#72]
### Project Description

We need a low-friction, easy-to-understand framework that allows freelance researchers to apply for microgrants that finance various types of content generation for the forum. This includes Research Summaries, Discussion Posts, Use Cases, Case Studies, and other forms of research.

### Work Plan

- [ ] Publish a clear set of documents that explain the program
- [ ] Create content team approvals process for proposed content
- [ ] Create onboarding pack and chat mentoring process
- [ ] Clarify disbursement mechanisms

### Resources

- [Proposal](https://docs.google.com/document/d/1jhEI8GGUrZTRtXhNt3KnopF9JIa0Jf2x5BnFCS1SCDY/edit#heading=h.dcmwl8ij3xe)

**Comment by ghettodev** [comment]
@visavishesh @cipherix Can you guys please add some additional clarity about how we can prefilter content to keep overhead to a minimum. Some process breakdown in the doc would be great.

**Comment by ghettodev** [comment]
Ideas:

- Proposals are entered into GH
- Core research team adopts new researchers
- bounty/grant is approved
- etc...

**Comment by eleventh19** [comment]
@ghettodev should we close this or smartcontractresearchforum/operations#45 ? Unless we want to keep this open for other micro-grant ideas

**Comment by ghettodev** [comment]
This one got morphed into the https://github.com/smartcontractresearchforum/docs/blob/main/en/grants_general_contributors.md doc. I've updated the description. 

Should probably break out the other tasks into new issues or link them to existing tickets...

**Comment by eleventh19** [comment]
@eleventh19 make consistent with Pan African, Impact Awards, and smartcontractresearchforum/research_team#119

**Comment by eleventh19** [comment]
This is technically being done under smartcontractresearchforum/research_team#155 with the update of all github docs once the branding exercise advances a bit. I think is ready to be closed out as the link to the grant is above and the only remaining task is updating the doc. the other tasks are being taken care of elsewhere, will update the tags for them and then will confirm if there's anything else that needs to be done

**Comment by eleventh19** [comment]
should see if this is or should be linked to smartcontractresearchforum/research_team#108

**Comment by eleventh19** [comment]
this is also being worked on as part of the updates to researcher onboarding, the content pipeline process, and hiring researchers/peer reviewers

**Comment by eleventh19** [comment]
@ghettodev what's the next milestone we want to hit here? do we want to focus on grants for non research summary forum posts?

**Comment by encore9870** [comment]
This is something the smartcontractresearchforum/core-projects#1 should own.
