### ISSUE TITLE
Project: Markup Onboarding documents

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#73]
### Project Description

Onboarding documents need to be accessible to new researchers during the onboarding process, and available to the wider community. This project will shift completed documents from the shared drive to our Github repository.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Check that the Onboarding PPT is aligned with any recent changes
- [ ] Convert to MD and post to the forum
- [ ] Check that the Document Pipeline is aligned with any recent changes
- [ ] Convert to MD and post to forum
- [ ] Check that Research Mandate is complete and aligned with any recent changes
- [ ] Convert to MD and post to forum
- [ ] Check that the Onboarding FAQ is aligned with any recent changes
- [ ] Convert to MD and post to the forum

### Resources

- [Onboarding PPT](https://docs.google.com/presentation/d/16CKiR0xkN82Ax5uk9OYS8KWOmW3LHEKK32TB9bSL9ps/edit#slide=id.p)
- [Document Pipeline](https://docs.google.com/document/d/1Dxl4mpLQ01QrSvJC7HAl3xWR92aiIo4QgFwyk9w53Hk/edit)
- [Research Mandate](https://docs.google.com/document/d/1qkpj-aHYQ_uHVRYxZUHrQJJu2T6wvNMJDxHp2xXXygw/edit)
- [Onboarding FAQ](https://docs.google.com/document/d/1EyvVG45Rbk1AMo6YZfZ43UHPxJqF7aLxfihanvEkrZ8/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
When the new version of the go-to-market plan is ready, we should add that too
