### ISSUE TITLE
Project: Create documentation for onboarding casual researchers who are more interested in commenting

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#76]
### Project Description

Based on an idea Jerry Ho had for approaching researchers who might not be ready to write a full-fledged summary, this material would introduce the concept of SCRF without going into detail about how to create a research summary. First assignment is to create two substantial comments on the board.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Introduce the idea to Ops
- [ ] Create presentation
- [ ] Present to Research Team
- [ ] Refine based on suggestions
- [ ] Finalize payment details (after other docs have been onboarded)
- [ ] Convert to Markdown and post on site

### Resources

- [link to presentation](https://docs.google.com/presentation/d/1ua4olXZ-Y5yEed9vsQk3yb_zfPnuDixNvlKdu76RjC0/edit#slide=id.gccc0d9935a_0_329)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
@29988122 I've added you in case you have some feedback, I'll be doing a presentation tomorrow during the meeting and will send you a copy of the PPT afterwards

**Comment by encore9870** [comment]
This is now an engagement project where they are designing bounties for this purpose. Closing since the ticket itself is no longer relevant.
