### ISSUE TITLE
Project: Subscription to Adobe Stock

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#81]
### Project Description

Images increase engagement and add professional polish. Adobe's Stock footage archive contains many excellent tech-related images, templates, videos, 3D renders. 

[Pricing from Adobe ](https://stock.adobe.com/sg/plans)

**Content:** Professional stock imagery would make articles and discussions posts more visually appealing.
**Engagement:** Graphics increase [engagement](https://www.mdgadvertising.com/marketing-insights/infographics/its-all-about-the-images-infographic/).
**Outreach:** Add professional polish to documents.
**Discovery:** Add professional polish to documents.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Investigate pricing 
- [x] Present to Ops
- [ ] Present to Engagement Team
- [ ] Decide level (suggest 40/month)
- [ ] Purchase subscription
- [ ] Assess periodically

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by jamesmcgirk** [comment]
@ghettodev suggests that we use Stocksy instead. Next step would be comparing pricing to Adobe.

**Comment by jamesmcgirk** [comment]
Contacted corporate HQ to make sure they don't already have an arrangement.

**Comment by jamesmcgirk** [comment]
Use an NFT, point out to Rich when we need something.
