### ISSUE TITLE
Present SCRF Project Plan to the team on Wed April 21

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#82]
- [ ] April 9 Define SCRF quarterly goals
- [ ] April 12 Define department-level goals & assign projects
- [ ] April 12-14 fill out quarterly project targets
- [ ] April 14 Review quarterly project targets
