### ISSUE TITLE
Project: Engagement Opportunity for Recent Grads (AMAs)

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_team#83]
### Project Description

The process of curating papers and generating Research Pulse could be further used to create engagement opportunities. Recent grads are particularly eager to discuss their papers, but due to the peer review process, their publications are siloed in paywallet academic journals. Identifying recent grads after Research Pulse curation can result in more targeted outreach and ultimately bring more industry researchers to the forum. As part of outreach, we can create a new Ask-Me-Anything (AMA) content type as a strategy to get them onboard.

### Workplan

- [x] Scope ways of automating the collection of data from academic institutions
- [x] Begin selecting the first batch of candidates with Research Pulse and assess how long it takes to source information on Recent Grads.
- [ ] Reach out to first batch of candidates
- [ ] Coordinate with Research Team on targeted questions on AMA
- [ ] Publish AMA with first author

### Project Plan

https://docs.google.com/document/d/1K6FwKZC3fBVbZFdq6hSGDDPeIWYPWDnPp9pS17pl0Yk/edit?usp=sharing

**Comment by eleventh19** [comment]
I believe this is completed as we've had the [AMA with the BitML authors](https://www.smartcontractresearch.org/t/a-conversation-with-the-creators-of-bitml/437#a-conversation-with-the-creators-of-bitml-1)

**Comment by encore9870** [comment]
This is a good idea and we are applying the notion to primary author outreach and/or impact awards (after its relaunch). Closing since the ticket is no longer relevant.
