### ISSUE TITLE
Project: Expanding GtM Tracking Spreadsheet (adding additional entries)

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#93]
### Project Description

Much of the content on the board has yet to have a GtM strategy, this is the first step.

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Cross-reference existing entries with SCRF 
- [x] Update as needed
- [ ] Cross-reference with GitHub
- [ ] Cross-reference with Google Drive
- [ ] Identify promising candidates for ET attention

### Resources

- [link to project plan](#linkme)
- [link to process doc/proof of concept](#linkme)
- [link to any other relevant supporting materials](#linkme)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

_**Provide updates to this ticket at regular intervals**. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF._

_Ensure the correct tags and projects have been selected in the sidebar -->_

**Comment by eleventh19** [comment]
@jamesmcgirk @zubepaul are there any open tasks relating to this?

**Comment by zubepaul** [comment]
None that I am aware of.
